### ISSUE TITLE
Installation instruction

### ISSUE THREAD

**Issue by Collizo4sky** [Peekmo/atom-autocomplete-php#10]
How do i install this on Atom

**Comment by Peekmo** [comment]
Hello,

It depends on your system, on Linux and OSX, just clone the project into ~/.atom/packages and reload your editor, or (cleaner), clone it into ~/github and set a symbolic link into ~/.atom/packages to ~/github/atom-autocomplete-php
For Windows, I don't know, check where the plugins are installed.
The package will be also available in the package manager soon (I haven't got a lot of time this week, but it's planned)

Regards,
Peekmo

**Comment by Collizo4sky** [comment]
I will wait for it to be available on Atom package list.

**Comment by Collizo4sky** [comment]
@Peekmo i did copy the package to `~\.atom\packages` on windows but got the error below after reloading atom.


```
Cannot find module 'fuzzaldrin'
Hide Stack Trace
Error: Cannot find module 'fuzzaldrin'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (C:\Users\collizo4sky\AppData\Local\atom\app-0.194.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/C:/Users/collizo4sky/.atom/packages/atom-autocomplete-php/lib/providers/class-provider.coffee:6:16)
    at Object.<anonymous> (/C:/Users/collizo4sky/.atom/packages/atom-autocomplete-php/lib/providers/class-provider.coffee:112:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (C:\Users\collizo4sky\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```

**Comment by Peekmo** [comment]
Ho yes sorry, I forgot, you must run "npm install" in cloned folder to install dependencies (You must have nodejs installed, but I think that you already have it)

**Comment by Collizo4sky** [comment]
After running `npm install` to install the dependencies. i got the errors below


```
Cannot read property 'length' of undefined
Hide Stack Trace
TypeError: Cannot read property 'length' of undefined
    at Object.module.exports.writeConfig (/C:/Users/collizo4sky/.atom/packages/autocomplete-php/lib/config.coffee:27:32)
    at Object.module.exports.init (/C:/Users/collizo4sky/.atom/packages/autocomplete-php/lib/config.coffee:40:12)
    at Object.module.exports.activate (/C:/Users/collizo4sky/.atom/packages/atom-autocomplete-php/lib/peekmo-php-atom-autocomplete.coffee:45:14)
    at Package.module.exports.Package.activateNow (C:\Users\collizo4sky\AppData\Local\atom\app-0.194.0\resources\app.asar\src\package.js:222:19)
    at C:\Users\collizo4sky\AppData\Local\atom\app-0.194.0\resources\app.asar\src\package.js:203:30
    at Package.module.exports.Package.measure (C:\Users\collizo4sky\AppData\Local\atom\app-0.194.0\resources\app.asar\src\package.js:147:15)
    at Package.module.exports.Package.activate (C:\Users\collizo4sky\AppData\Local\atom\app-0.194.0\resources\app.asar\src\package.js:195:14)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\collizo4sky\AppData\Local\atom\app-0.194.0\resources\app.asar\src\package-manager.js:434:21)
    at C:\Users\collizo4sky\AppData\Local\atom\app-0.194.0\resources\app.asar\src\package-manager.js:418:29
    at Config.module.exports.Config.transact (C:\Users\collizo4sky\AppData\Local\atom\app-0.194.0\resources\app.asar\src\config.js:311:16)
```


What do you think?

**Comment by Collizo4sky** [comment]
I also got the following notices


```
Requiring $ from atom is no longer supported. If you are using space-pen, please require $ from atom-space-pen-views. Otherwise require jquery instead: {$} = require 'atom-space-pen-views' or $ = require 'jquery' Add "atom-space-pen-views": "^2.0.3" to your package dependencies. Or add "jquery": "^2" to your package dependencies.
Called 1 timeCreate Issue on autocomplete-php repo
Object.Object.defineProperty.get - C:\Users\collizo4sky\AppData\Local\atom\app-0.194.0\resources\app.asar\exports\atom.js:48:11
Object.<anonymous> - C:\Users\collizo4sky\.atom\packages\autocomplete-php\lib\providers\class-provider.coffee:7:1
Object.<anonymous> - C:\Users\collizo4sky\.atom\packages\autocomplete-php\lib\providers\class-provider.coffee:112:4
Module._compile - module.js:452:26
Requiring $ from atom is no longer supported. If you are using space-pen, please require $ from atom-space-pen-views. Otherwise require jquery instead: {$} = require 'atom-space-pen-views' or $ = require 'jquery' Add "atom-space-pen-views": "^2.0.3" to your package dependencies. Or add "jquery": "^2" to your package dependencies.
Called 1 timeCreate Issue on autocomplete-php repo
Object.Object.defineProperty.get - C:\Users\collizo4sky\AppData\Local\atom\app-0.194.0\resources\app.asar\exports\atom.js:48:11
Object.<anonymous> - C:\Users\collizo4sky\.atom\packages\autocomplete-php\lib\providers\static-provider.coffee:7:1
Object.<anonymous> - C:\Users\collizo4sky\.atom\packages\autocomplete-php\lib\providers\static-provider.coffee:104:4
Module._compile - module.js:452:26
Requiring $$ from atom is no longer supported. Please require atom-space-pen-views instead: {$$} = require 'atom-space-pen-views' Add "atom-space-pen-views": "^2.0.3" to your package dependencies.
Called 1 timeCreate Issue on autocomplete-php repo
Object.Object.defineProperty.get - C:\Users\collizo4sky\AppData\Local\atom\app-0.194.0\resources\app.asar\exports\atom.js:54:11
Object.<anonymous> - C:\Users\collizo4sky\.atom\packages\autocomplete-php\lib\providers\class-provider.coffee:7:4
Object.<anonymous> - C:\Users\collizo4sky\.atom\packages\autocomplete-php\lib\providers\class-provider.coffee:112:4
Module._compile - module.js:452:26
Requiring $$ from atom is no longer supported. Please require atom-space-pen-views instead: {$$} = require 'atom-space-pen-views' Add "atom-space-pen-views": "^2.0.3" to your package dependencies.
Called 1 timeCreate Issue on autocomplete-php repo
Object.Object.defineProperty.get - C:\Users\collizo4sky\AppData\Local\atom\app-0.194.0\resources\app.asar\exports\atom.js:54:11
Object.<anonymous> - C:\Users\collizo4sky\.atom\packages\autocomplete-php\lib\providers\static-provider.coffee:7:4
Object.<anonymous> - C:\Users\collizo4sky\.atom\packages\autocomplete-php\lib\providers\static-provider.coffee:104:4
Module._compile - module.js:452:26
Store package style sheets in the styles/ directory instead of stylesheets/ in the autocomplete-php package
Called 1 timeCreate Issue on autocomplete-php repo
Package.getStylesheetsPath - C:\Users\collizo4sky\AppData\Local\atom\app-0.194.0\resources\app.asar\src\package.js:430:9
Package.getStylesheetPaths - C:\Users\collizo4sky\AppData\Local\atom\app-0.194.0\resources\app.asar\src\package.js:441:32
Package.loadStylesheets - C:\Users\collizo4sky\AppData\Local\atom\app-0.194.0\resources\app.asar\src\package.js:423:38
<unknown> - C:\Users\collizo4sky\AppData\Local\atom\app-0.194.0\resources\app.asar\src\package.js:167:19
```

**Comment by Peekmo** [comment]
For the problem, it could be a lot of things. 

Note that the plugin works only for a project with composer, with a command "php" available. You have some settings for the plugin that you can change. It seems that you are on windows, I never tested on it.

For the notices, I would like to know where you found them ? I'm on atom 0.194 like you and I haven't got them.

Regards,
Peekmo

**Comment by Collizo4sky** [comment]
It will be best i wait till it's available on Atom package manager.

**Comment by Collizo4sky** [comment]
Clicking on the yellow icon reveals the deprecated errors.


![atom-php](https://cloud.githubusercontent.com/assets/4140659/7399401/951bfc34-eead-11e4-9128-90441809b371.png)

**Comment by Peekmo** [comment]
Not sure if it will be best ^^ All tests are welcome to improve the package ;)

Thank you for the tip for deprecated errors, they are all fixes with the last commit :)

Regards,
Peekmo

**Comment by Collizo4sky** [comment]
A bit‎ disheartening I can't get it to work on Windows.By the way, does the package depend on the `auto-complete` package?                                                                                                                                                                                                                                         From: Axel AnceauSent: Thursday, 30 April 2015 6:54 AMTo: Peekmo/atom-autocomplete-phpReply To: Peekmo/atom-autocomplete-phpCc: Agbonghama CollinsSubject: Re: [atom-autocomplete-php] Installation instruction (#10)Not sure if it will be best ^^ All tests are welcome to improve the package ;)

Thank you for the tip for deprecated errors, they are all fixes with the last commit :)

Regards,
Peekmo

—Reply to this email directly or view it on GitHub.

**Comment by Peekmo** [comment]
It depends on the 'autocomplete-plus' package.

When you have an error in the top right of the editor, you have a button 'create an issue on the ... package', could you please use this link, in order to have more informations about your problem ?

Thank you

**Comment by Collizo4sky** [comment]
I deleted my previous installed and install a fresh version using Atom package manager.

It seems you've published the package to Atom package manager :+1: 

Works perfectly albeit the autocomplete isn't very intelligent compare to the ones in IDEs like PhpStorm.

**Comment by Peekmo** [comment]
Hello,

Nop, I didn't submit it to the atom package manager.

It's an other one, with less features that is in Atom package manager.

Regards,
Peekmo
