### ISSUE TITLE
Uncaught TypeError: Cannot read property 'row' of null

### ISSUE THREAD

**Issue by teamoceancode** [Peekmo/atom-autocomplete-php#122]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.18
**System**: Mac OS X 10.10.5
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.10.12

### Stack Trace

Uncaught TypeError: Cannot read property 'row' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:809

TypeError: Cannot read property 'row' of null
    at Object.module.exports.getStackClasses (/Users/Teamoceancode/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:263:11)
    at GotoFunction.module.exports.AbstractGoto.getCalledClass (/Users/Teamoceancode/.atom/packages/atom-autocomplete-php/lib/goto/abstract-goto.coffee:223:28)
    at GotoFunction.module.exports.GotoFunction.getMethodForTerm (/Users/Teamoceancode/.atom/packages/atom-autocomplete-php/lib/goto/function-goto.coffee:156:28)
    at GotoFunction.<anonymous> (/Users/Teamoceancode/.atom/packages/atom-autocomplete-php/lib/goto/function-goto.coffee:204:26)
    at GotoFunction.module.exports.GotoFunction.registerMarkers (/Users/Teamoceancode/.atom/packages/atom-autocomplete-php/lib/goto/function-goto.coffee:198:13)
    at /Users/Teamoceancode/.atom/packages/atom-autocomplete-php/lib/goto/abstract-goto.coffee:35:18
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1037:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1004:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:584:26)
```

### Commands

```
     -0:20.9.0 atom-autocomplete-php:goto (atom-text-editor.editor.is-focused)
     -0:19 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:19 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:17.2.0 atom-autocomplete-php:goto (atom-text-editor.editor.is-focused)
     -0:14.8.0 editor:delete-to-beginning-of-subword (atom-text-editor.editor.is-focused)
     -0:13.5.0 core:undo (atom-text-editor.editor.is-focused)
  2x -0:12.8.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:10.7.0 atom-autocomplete-php:goto (atom-text-editor.editor.is-focused)
     -0:08.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
  3x -0:08.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  2x -0:07.3.0 core:save (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-seti-ui)
     -0:04.1.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:04.1.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:01.9.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:01.9.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:01.2.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "wrap-guide",
      "emmet"
    ]
  },
  "atom-autocomplete-php": {}
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.7.4
angularjs, v0.3.0
atom-alignment, v0.12.1
atom-autocomplete-php, v0.10.12
autocomplete-php, v0.3.7
cdn-libs, v0.0.3
change-case, v0.6.0
codeigniter, v0.2.0
docblockr, v0.7.3
language-blade, v0.15.0
laravel, v0.7.0
seti-ui, v0.8.0
terminal-panel, v1.14.1

# Dev
No dev packages
```

**Comment by RaoulDijksman** [comment]
I have the same problem:

1. Startup Atom

**Atom Version**: 1.0.7
**System**: linux 4.1.6-1-ARCH
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.10.12


### Stack Trace

Failed to activate the atom-autocomplete-php package

```
At Cannot read property 'row' of null

TypeError: Cannot read property 'row' of null
    at Object.module.exports.getStackClasses (/home/raoul/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:235:43)
    at GotoFunction.module.exports.AbstractGoto.getCalledClass (/home/raoul/.atom/packages/atom-autocomplete-php/lib/goto/abstract-goto.coffee:329:30)
    at GotoFunction.module.exports.GotoFunction.getMethodForTerm (/home/raoul/.atom/packages/atom-autocomplete-php/lib/goto/function-goto.coffee:167:28)
    at GotoFunction.<anonymous> (/home/raoul/.atom/packages/atom-autocomplete-php/lib/goto/function-goto.coffee:221:26)
    at GotoFunction.module.exports.GotoFunction.registerMarkers (/home/raoul/.atom/packages/atom-autocomplete-php/lib/goto/function-goto.coffee:292:12)
    at /home/raoul/.atom/packages/atom-autocomplete-php/lib/goto/abstract-goto.coffee:52:17
    at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app.asar/src/workspace.js:276:9)
    at GotoFunction.module.exports.AbstractGoto.init (/home/raoul/.atom/packages/atom-autocomplete-php/lib/goto/abstract-goto.coffee:46:22)
    at GotoManager.module.exports.GotoManager.init (/home/raoul/.atom/packages/atom-autocomplete-php/lib/goto/goto-manager.coffee:34:14)
    at Object.module.exports.activate (/home/raoul/.atom/packages/atom-autocomplete-php/lib/peekmo-php-atom-autocomplete.coffee:60:24)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tabs-to-spaces",
      "autocomplete-php",
      "php-analyser",
      "php-composer-completion",
      "git-history"
    ]
  },
  "atom-autocomplete-php": {
    "autoloadPaths": [
      "vendor/autoload.php"
    ],
    "classMapFiles": [
      "vendor/composer/autoload_classmap.php"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.10.12
auto-detect-indentation, v0.4.2
autocomplete-ruby, v0.1.0
file-icons, v1.6.9
laravel, v0.7.0
linter, v1.6.0
linter-php, v1.0.4
minimap, v4.13.4
pigments, v0.15.0

# Dev
No dev packages
```
