### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by alexandernst** [Peekmo/atom-autocomplete-php#123]
at execute (/home/alexandernst/.atom/packages/atom-autocomplete-php/lib/services/php-proxy.coffee:33:133)
    at Object.module.exports.methods (/home/alexandernst/.atom/packages/atom-autocomplete-php/lib/services/php-proxy.coffee:168:13)
    at GotoFunction.module.exports.GotoFunction.getMethodForTerm (/home/alexandernst/.atom/packages/atom-autocomplete-php/lib/goto/function-goto.coffee:162:25)
    at GotoFunction.module.exports.GotoFunction.getTooltipForWord (/home/alexandernst/.atom/packages/atom-autocomplete-php/lib/goto/function-goto.coffee:59:18)
    at HTMLSpanElement.<anonymous> (/home/alexandernst/.atom/packages/atom-autocomplete-php/lib/goto/abstract-goto.coffee:123:36)
    at HTMLDivElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

I get this with Atom 1.0.15 and this plugin 0.10.12

**Comment by alexandernst** [comment]
Also:

    at execute (/home/alexandernst/.atom/packages/atom-autocomplete-php/lib/services/php-proxy.coffee:33:133)
    at Object.module.exports.methods (/home/alexandernst/.atom/packages/atom-autocomplete-php/lib/services/php-proxy.coffee:168:13)
    at GotoFunction.module.exports.GotoFunction.getMethodForTerm (/home/alexandernst/.atom/packages/atom-autocomplete-php/lib/goto/function-goto.coffee:162:25)
    at GotoFunction.<anonymous> (/home/alexandernst/.atom/packages/atom-autocomplete-php/lib/goto/function-goto.coffee:204:26)
    at GotoFunction.module.exports.GotoFunction.registerMarkers (/home/alexandernst/.atom/packages/atom-autocomplete-php/lib/goto/function-goto.coffee:292:12)
    at /home/alexandernst/.atom/packages/atom-autocomplete-php/lib/goto/abstract-goto.coffee:37:14
    at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app.asar/src/workspace.js:276:9)
    at GotoFunction.module.exports.AbstractGoto.init (/home/alexandernst/.atom/packages/atom-autocomplete-php/lib/goto/abstract-goto.coffee:31:24)
    at GotoManager.module.exports.GotoManager.init (/home/alexandernst/.atom/packages/atom-autocomplete-php/lib/goto/goto-manager.coffee:20:18)
    at Object.module.exports.activate (/home/alexandernst/.atom/packages/atom-autocomplete-php/lib/peekmo-php-atom-autocomplete.coffee:57:18)

**Comment by alexandernst** [comment]
Sorry, my bad, This issues happens because of path php binary path.

**Comment by theking2** [comment]
I have this problem with php path set.
