### ISSUE TITLE
Cannot read property 'command' of undefined

### ISSUE THREAD

**Issue by alexandernst** [Peekmo/atom-autocomplete-php#17]
TypeError: Cannot read property 'command' of undefined
      at Object.module.exports.init (/home/alexandernst/.atom/packages/atom-autocomplete-php/lib/config.coffee:42:23)
      at Object.module.exports.activate (/home/alexandernst/.atom/packages/atom-autocomplete-php/lib/peekmo-php-atom-autocomplete.coffee:40:12)
      at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:238:19)
      at /usr/share/atom/resources/app.asar/src/package.js:219:30
      at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:163:15)
      at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:211:14)
      at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:451:21)
      at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:362:29
      at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
      at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
      at /usr/share/atom/resources/app.asar/src/buffered-process.js:220:18
      at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
      at emitOne (events.js:82:20)

**Comment by alexandernst** [comment]
This happens when I open Atom.

**Comment by Peekmo** [comment]
What is your version of atom ?

**Comment by alexandernst** [comment]
0.206, Debian Linux

**Comment by Peekmo** [comment]
In fact, thank you, I was using an old method to register a command that was working on 0.204.0 and not on 0.206.0. It should work now if you update the package.

**Comment by alexandernst** [comment]
Yay! It doesn't crash now, anyways, it's not working. I'm going to open another issue.

**Comment by Peekmo** [comment]
The plugin seems to not work well with the last version of atom.

Use atom --include-deprecated-apis to use it. I don't know why because I haven't got deprecations on the plugin. So, I need to learn more about changes.
