### ISSUE TITLE
Uncaught ReferenceError: func is not defined

### ISSUE THREAD

**Issue by itadar** [Peekmo/atom-autocomplete-php#189]
Error popping up by itself, i dont know how to trigger it.

**Atom Version**: 1.0.19
**System**: Microsoft Windows 10 Home
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.14.0

### Stack Trace

Uncaught ReferenceError: func is not defined

```
At /C:/Users/u205/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:439

ReferenceError: func is not defined
  at Object.module.exports.getVariableType (C:\Users\u205\.atom\packages\atom-autocomplete-php\lib\services\php-file-parser.coffee:509:77)
  at Object.module.exports.parseElements (C:\Users\u205\.atom\packages\atom-autocomplete-php\lib\services\php-file-parser.coffee:640:34)
  at Object.module.exports.getCalledClass (C:\Users\u205\.atom\packages\atom-autocomplete-php\lib\services\php-file-parser.coffee:34:17)
  at Object.module.exports.getMethodContext (C:\Users\u205\.atom\packages\atom-autocomplete-php\lib\services\php-file-parser.coffee:559:28)
  at FunctionProvider.module.exports.FunctionProvider.getTooltipForWord (C:\Users\u205\.atom\packages\atom-autocomplete-php\lib\tooltip\function-provider.coffee:18:25)
  at FunctionProvider.module.exports.AbstractProvider.showPopoverFor (C:\Users\u205\.atom\packages\atom-autocomplete-php\lib\tooltip\abstract-provider.coffee:108:24)
  at HTMLSpanElement.<anonymous> (C:\Users\u205\.atom\packages\atom-autocomplete-php\lib\tooltip\abstract-provider.coffee:77:22)
  at HTMLDivElement.jQuery.event.dispatch (C:\Users\u205\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at HTMLDivElement.elemData.handle (C:\Users\u205\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
     -5:53.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -5:52.7.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -5:51.8.0 core:save (atom-text-editor.editor.is-focused)
     -2:22.2.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -2:21.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:52 core:backspace (atom-text-editor.editor.is-focused)
     -1:51.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:46.4.0 core:cut (atom-text-editor.editor.is-focused)
     -1:45.3.0 core:save (atom-text-editor.editor.is-focused)
     -1:42.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:42.7.0 core:paste (atom-text-editor.editor.is-focused)
     -1:40.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:37.2.0 editor:duplicate-lines (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:30.8.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:24.1.0 editor:duplicate-lines (atom-text-editor.editor.is-focused)
     -1:19.5.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "lesscompile",
      "lesscompile"
    ]
  },
  "atom-autocomplete-php": {
    "autoloadPaths": [
      "classes/Autoloader.php"
    ],
    "binComposer": "php C:\\Users\\u205\\composer.phar"
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.14.0
atom-beautify, v0.28.14
autoclose-html, v0.19.0
autocomplete-modules, v1.3.0
coffee-compile, v0.19.1
color-picker, v2.0.13
keyboard-localization, v1.4.9
language-smarty-php, v0.5.0
minimap, v4.13.4
project-manager, v2.6.4
remote-sync, v3.1.2
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by Peekmo** [comment]
Hello,

The issue should be fixed.

Regards,
Peekmo
