### ISSUE TITLE
Uncaught TypeError: Cannot read property '59' of undefined

### ISSUE THREAD

**Issue by rafaelstz** [Peekmo/atom-autocomplete-php#193]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Ubuntu 14.04.3
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.14.1

### Stack Trace

Uncaught TypeError: Cannot read property '59' of undefined

```
At /home/webjump/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:304

TypeError: Cannot read property '59' of undefined
    at Object.module.exports.getStackClasses (/home/webjump/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:304:29)
    at Object.module.exports.getCalledClass (/home/webjump/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:29:21)
    at Object.module.exports.getMethodContext (/home/webjump/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:559:28)
    at FunctionProvider.module.exports.FunctionProvider.getTooltipForWord (/home/webjump/.atom/packages/atom-autocomplete-php/lib/tooltip/function-provider.coffee:18:25)
    at FunctionProvider.module.exports.AbstractProvider.showPopoverFor (/home/webjump/.atom/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:108:24)
    at HTMLSpanElement.<anonymous> (/home/webjump/.atom/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:77:22)
    at HTMLDivElement.jQuery.event.dispatch (/opt/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/opt/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  2x -2:13 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:12.4.0 tree-view:expand-directory (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  5x -2:12.2.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:11 tree-view:expand-directory (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  3x -2:10.5.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:10 tree-view:expand-directory (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  3x -2:09.6.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:18.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:18 core:paste (atom-text-editor.editor.is-focused)
     -1:12.6.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:12.5.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -1:07.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:17.9.0 fuzzy-finder:toggle-file-finder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:17.3.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:16.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 10x -0:09.4.0 core:page-down (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".modgit"
    ]
  },
  "atom-autocomplete-php": {}
}
```

### Installed Packages

```coffee
# User
SFTP-deployment, v1.0.2
atom-autocomplete-php, v0.14.1
atom-beautify, v0.28.14
php-cs-fixer, v2.5.0

# Dev
No dev packages
```

**Comment by hotoiledgoblinsack** [comment]
@Peekmo Strange, that seems to be the line `if lineText[i] == '('` in `getStackClasses`, I don't see any mention in the Atom documentation that the method `lineTextForBufferRow` can ever return undefined?

**Comment by Peekmo** [comment]
Why not if the line does not exists.

The more surprising thing, is that it doesn't exists ^^ I don't figure out how it's possible..
