### ISSUE TITLE
Uncaught TypeError: Cannot read property 'names' of undefined

### ISSUE THREAD

**Issue by valeriabarros** [Peekmo/atom-autocomplete-php#203]
In .atom/packages/atom-autocomplete-php/lib/autocompletion/function-provider.coffee:40

Detais of error

TypeError: Cannot read property 'names' of undefined
  at FunctionProvider.module.exports.FunctionProvider.fetchSuggestions (C:\Users\valeriabarros\.atom\packages\atom-autocomplete-php\lib\autocompletion\function-provider.coffee:27:23)
  at FunctionProvider.module.exports.AbstractProvider.getSuggestions (C:\Users\valeriabarros\.atom\packages\atom-autocomplete-php\lib\autocompletion\abstract-provider.coffee:30:17)
  at C:\Users\valeriabarros\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:286:56
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (C:\Users\valeriabarros\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:265:17)
  at AutocompleteManager.getSuggestionsFromProviders (C:\Users\valeriabarros\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3:61)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (C:\Users\valeriabarros\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:252:19)
  at C:\Users\valeriabarros\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3:61

**Comment by PrakharSrivastav** [comment]
I also got the same error. Writing below my logs for reference


**Atom Version**: 1.5.4
**System**: Linux Mint
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.18.7


### Stack Trace

Uncaught TypeError: Cannot read property 'names' of undefined

```
At /home/prakhar/.atom/packages/atom-autocomplete-php/lib/autocompletion/function-provider.coffee:27

TypeError: Cannot read property 'names' of undefined
    at FunctionProvider.module.exports.FunctionProvider.fetchSuggestions (/home/prakhar/.atom/packages/atom-autocomplete-php/lib/autocompletion/function-provider.coffee:27:23)
    at FunctionProvider.module.exports.AbstractProvider.getSuggestions (/home/prakhar/.atom/packages/atom-autocomplete-php/lib/autocompletion/abstract-provider.coffee:30:17)
    at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:290:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:269:17)
    at AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:256:19)
    at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
     -0:33.8.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:31 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:09.1.0 grammar-selector:show (atom-text-editor.editor)
     -0:04.6.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:04.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:04.2.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:04.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:02.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:02.3.0 core:cancel (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "language-csharp",
      "language-perl",
      "language-ruby",
      "language-ruby-on-rails",
      "language-coffee-script",
      "language-clojure",
      "language-c",
      "language-go",
      "language-java",
      "language-make",
      "language-mustache",
      "language-objective-c",
      "metrics",
      "language-less",
      "language-python",
      "language-sass",
      "language-toml",
      "timecop",
      "goto-definition",
      "laravel",
      "codeigniter",
      "jQuery"
    ]
  },
  "atom-autocomplete-php": {}
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.7
docblockr, v0.7.3
emmet-simplified, v2.5.0
language-blade, v0.20.0
php-cs-fixer, v2.5.6
php-integrator-autocomplete-plus, v0.5.2
php-integrator-base, v0.6.9
php-integrator-navigation, v0.5.0
project-manager, v2.7.6
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by signmein** [comment]
I also got this error.

**Comment by Peekmo** [comment]
Should be fixed with the last release.
