### ISSUE TITLE
Uncaught Error: Cannot find module '../services/php-proxy.coffee'

### ISSUE THREAD

**Issue by DDiimmkkaass** [Peekmo/atom-autocomplete-php#215]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Ubuntu 14.04.3
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.18.4

### Stack Trace

Uncaught Error: Cannot find module '../services/php-proxy.coffee'

```
At module.js:338

Error: Cannot find module '../services/php-proxy.coffee'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at ClassProvider.module.exports.ClassProvider.getTooltipForWord (/home/ddiimmkkaass/.atom/packages/atom-autocomplete-php/lib/tooltip/class-provider.coffee:20:17)
    at ClassProvider.module.exports.AbstractProvider.showPopoverFor (/home/ddiimmkkaass/.atom/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:109:24)
    at HTMLSpanElement.<anonymous> (/home/ddiimmkkaass/.atom/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:78:22)
    at HTMLDivElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -9:05.9.0 command-palette:toggle (atom-text-editor.editor.mini.is-focused)
     -9:04.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -9:04.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  5x -9:03.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  5x -9:00.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -8:44.2.0 pane:split-left (a.icon.icon-package)
     -8:30.3.0 pane:close (ul.list-inline.tab-bar.inset-panel)
  5x -8:20.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -6:23 core:cancel (div.package-detail.panels-item)
  3x -6:05.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -5:48.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -3:08.3.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -3:03.9.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -3:03.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:02.5.0 core:save (atom-text-editor.editor.is-focused)
     -2:59 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-php, v0.3.7
php-composer-completion, v0.3.4
php-integrator-navigation, v0.2.4

# Dev
No dev packages
```

**Comment by Peekmo** [comment]
Hello,

Try to remove / reinstall the package. The problem is really weird, and I think that it's more a cache issue than this package's issue (regarding to your stacktrace)

Regards,
Peekmo

**Comment by Mujaddadi** [comment]
Same error

**Comment by raciniak** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Ubuntu 15.10
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.18.7


### Stack Trace

Uncaught Error

```
At /home/username/.atom/packages/atom-autocomplete-php/lib/services/php-proxy.coffee:116

undefined
```

### Commands

```
     -0:35 command-palette:toggle (atom-text-editor.editor.is-focused)
 11x -0:29.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:19.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:19.1.0 php-integrator-autocomplete-plus:sort-use-statements (atom-text-editor.editor)
     -0:12.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:07.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:07.9.0 autocomplete-plus:activate (atom-text-editor.editor)
     -0:06.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:03.4.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:02.4.0 core:move-up (atom-text-editor.editor.mini.is-focused)
  2x -0:01.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:00.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.9.0 atom-autocomplete-php:namespace (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-gfm",
      "language-csharp",
      "language-java"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "seti-ui",
      "monokai-seti"
    ]
  },
  "atom-autocomplete-php": {}
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.7
autoclose-html, v0.23.0
autocomplete-jquery-mobile, v0.2.2
autocomplete-json, v1.9.1
autocomplete-plus, v2.29.1
jQuery, v1.2.1
jquery-snippets, v11.0.0
language-ini, v1.14.0
language-markdown, v0.11.0
language-pascal, v0.17.0
language-smarty-php, v0.5.0
linter, v1.11.3
linter-csslint, v1.3.2
linter-htmlhint, v1.0.3
linter-jshint, v2.0.2
linter-php, v1.2.0
minimap, v4.20.0
monokai-seti, v0.7.0
open-recent, v5.0.0
php-debug, v0.2.2
php-getters-setters, v0.5.5
php-integrator-autocomplete-plus, v0.5.2
php-twig, v4.0.0
pigments, v0.24.5
robin-language-php, v0.9.0
seti-icons, v0.4.5
seti-ui, v0.9.1
symbols-tree-view, v0.11.0
terminal-plus, v0.14.5
wakatime, v5.0.8

# Dev
No dev packages
```

**Comment by andergmartins** [comment]
Same error, please reopen this. Just installed, uninstalled, installed again... and it is still an issue.

**Comment by mortenn** [comment]
Completely clean install, getting this.
