### ISSUE TITLE
Uncaught TypeError: Cannot read property 'entryAction' of undefined

### ISSUE THREAD

**Issue by CaredduMattia** [Peekmo/atom-autocomplete-php#221]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.0-beta3
**System**: Ubuntu 15.10
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.18.4

### Stack Trace

Uncaught TypeError: Cannot read property 'entryAction' of undefined

```
At /usr/share/atom-beta/resources/app.asar/src/pane.js:829

TypeError: Cannot read property 'entryAction' of undefined
    at Object.module.exports.getMemberContext (/home/ryuk/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:685:32)
    at FunctionProvider.module.exports.FunctionProvider.extractAnnotationInfo (/home/ryuk/.atom/packages/atom-autocomplete-php/lib/annotation/method-provider.coffee:17:27)
    at FunctionProvider.module.exports.AbstractProvider.placeAnnotation (/home/ryuk/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:103:27)
    at FunctionProvider.<anonymous> (/home/ryuk/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:92:18)
    at FunctionProvider.module.exports.AbstractProvider.registerAnnotations (/home/ryuk/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:91:13)
    at FunctionProvider.module.exports.AbstractProvider.rescan (/home/ryuk/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:236:10)
    at /home/ryuk/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:24:18
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1067:27)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1037:19)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom-beta/resources/app.asar/src/text-editor.js:602:26)
    at Pane.module.exports.Pane.saveItem (/usr/share/atom-beta/resources/app.asar/src/pane.js:534:18)
    at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom-beta/resources/app.asar/src/pane.js:517:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom-beta/resources/app.asar/src/workspace.js:643:35)
    at atom-workspace.commandRegistry.add.core:save (/usr/share/atom-beta/resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom-beta/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom-beta/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom-beta/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom-beta/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom-beta/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/usr/share/atom-beta/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
 17x -4:25.1.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:20.1.0 core:cut (atom-text-editor.editor.is-focused)
     -4:18.8.0 core:undo (atom-text-editor.editor.is-focused)
     -3:20.5.0 settings-view:open (atom-text-editor.editor.is-focused)
     -3:12.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:39.7.0 editor:newline (atom-text-editor.editor.is-focused)
 13x -2:36.6.0 core:select-left (atom-text-editor.editor.is-focused)
     -2:34.9.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -2:34.5.0 core:save (atom-text-editor.editor.is-focused)
     -1:16.6.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:44.9.0 core:backspace (atom-text-editor#atom-autocomplete-php.binPhp.editor.mini.is-focused)
     -0:44.1.0 core:confirm (atom-text-editor#atom-autocomplete-php.binPhp.editor.mini.is-focused)
     -0:32.8.0 settings-view:open (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
 21x -0:07.4.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:01.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:00.7.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "atom-autocomplete-php": {
    "binComposer": "/usr/bin/composer.phar"
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.4
atom-symfony2, v0.2.1

# Dev
No dev packages
```

**Comment by Peekmo** [comment]
Hello,
Should be fixed.

Regards,
Peekmo
