### ISSUE TITLE
Uncaught TypeError: marker.destroy is not a function

### ISSUE THREAD

**Issue by roelofr** [Peekmo/atom-autocomplete-php#222]
Steps to reproduce

1. Open a file
2. Press <kbd>Ctrl</kbd>+<kbd>S</kbd>
3. Behold

This error seems to occur whenever trying to save a file using the <kbd>Ctrl</kbd>+<kbd>S</kbd> hotkey on any file. The previous issue seems to only mention Ruby and Gemfiles, but I've been able to trigger the error on `Gruntfile.js`, a simple JSON file and PHP files (basically any file).

Given that the previous error had gone cold, this might very well be a client-side error (something I misconfigured or that was installed incorrectly), might even say *PEBKAC*...

**Atom Version**: 1.3.3
**System**: Microsoft Windows 10 Pro
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.18.4

### Stack Trace

Uncaught TypeError: marker.destroy is not a function

```
At C:\Users\roelof\AppData\Local\atom\app-1.3.3\resources\app.asar\src\pane.js:829

TypeError: marker.destroy is not a function
    at FunctionProvider.module.exports.AbstractProvider.removeAnnotations (file:///C:/Users/roelof/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:224:20)
    at FunctionProvider.module.exports.AbstractProvider.rescan (file:///C:/Users/roelof/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:235:10)
    at file:///C:/Users/roelof/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:24:18
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\roelof\AppData\Local\atom\app-1.3.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\roelof\AppData\Local\atom\app-1.3.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\roelof\AppData\Local\atom\app-1.3.3\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1060:27)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\roelof\AppData\Local\atom\app-1.3.3\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1030:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\roelof\AppData\Local\atom\app-1.3.3\resources\app.asar\src\text-editor.js:602:26)
    at Pane.module.exports.Pane.saveItem (C:\Users\roelof\AppData\Local\atom\app-1.3.3\resources\app.asar\src\pane.js:534:18)
    at Pane.module.exports.Pane.saveActiveItem (C:\Users\roelof\AppData\Local\atom\app-1.3.3\resources\app.asar\src\pane.js:517:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\roelof\AppData\Local\atom\app-1.3.3\resources\app.asar\src\workspace.js:633:35)
    at atom-workspace.commandRegistry.add.core:save (C:\Users\roelof\AppData\Local\atom\app-1.3.3\resources\app.asar\src\register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\roelof\AppData\Local\atom\app-1.3.3\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\roelof\AppData\Local\atom\app-1.3.3\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\roelof\AppData\Local\atom\app-1.3.3\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\roelof\AppData\Local\atom\app-1.3.3\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\roelof\AppData\Local\atom\app-1.3.3\resources\app.asar\src\window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (C:\Users\roelof\AppData\Local\atom\app-1.3.3\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -2:15.4.0 core:select-up (atom-text-editor.editor.is-focused)
     -2:15 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -2:14.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:13.2.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -2:11.7.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -2:10.9.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -2:10.6.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -2:10.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:09.7.0 editor:newline (atom-text-editor.editor.is-focused)
  5x -2:05.2.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -2:02.4.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "metrics",
      "windows-carriage-return-remover",
      "restore-windows",
      "you-complete-me",
      "autoflow",
      "spell-check",
      "dev-live-reload",
      "silent-sync",
      "Remote-FTP",
      "vim-mode",
      "refactor",
      "js-refactor",
      "typewriter",
      "language-hyperlink",
      "link",
      "welcome",
      "atom-phpcs"
    ],
    "autoHideMenuBar": true,
    "projectHome": "D:\\development",
    "followSymlinks": true,
    "packagesWithKeymapsDisabled": [
      "notifications",
      "tree-view",
      "weather"
    ],
    "destroyEmptyPanes": false
  },
  "atom-autocomplete-php": {
    "binComposer": "C:\\ProgramData\\ComposerSetup\\bin\\composer",
    "binPhp": "C:\\tools\\php\\php",
    "insertNewlinesForUseStatements": true
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.4
atom-beautify, v0.28.21
atom-easy-jsdoc, v4.2.0
atom-symfony2, v0.2.1
build, v0.52.0
build-grunt, v0.4.0
build-make, v0.7.0
color-picker, v2.0.14
css-snippets, v0.9.0
file-type-icons, v0.7.4
irc, v0.4.0
jslint, v1.5.1
language-gmod-lua, v0.4.0
language-javascript-better, v1.7.1
language-latex, v0.6.1
language-pfm, v0.82.0
language-pgsql, v0.2.0
linter, v1.11.3
linter-jscs, v3.2.2
linter-jshint, v1.2.2
linter-just-say-no, v0.6.0
linter-less, v2.3.3
linter-lua, v1.0.1
linter-markdownlint, v1.0.1
linter-tidy, v1.0.1
minimap, v4.19.0
minimap-git-diff, v4.1.8
minimap-linter, v1.1.1
monokai, v0.18.0
pdf-view, v0.39.0
php-twig, v4.0.0
project-view, v0.4.1
remote-sync, v3.5.0
sass-autocompile, v0.12.2
sync-settings, v0.6.0
time-status, v1.1.0
travis-ci-status, v1.0.0
tree-view-git-status, v0.2.2

# Dev
No dev packages
```

**Comment by Peekmo** [comment]
Hello,

You're not the first that report this issue in fact. I never reproduced it so that's really hard to debug.
What are the steps exactly ?

PHP file opened, then your Gruntfile in the same window. Or there is no PHP file in your project ? Do you reproduce it everytime ?

Regards,
Peekmo

**Comment by roelofr** [comment]
Okay, this seems to reproduce it (I've ran this on Windows 10 Pro and on Debian Jessie)

I've started atom from a directory, say `~/my-project`, which is completely empty.
Then I create a new file, `README.md`, I put in some dummy content and hit <kbd>CTRL</kbd>+<kbd>S</kbd>.
The error `marker.destroy is not a function` is show (see below).
![markdown](https://cloud.githubusercontent.com/assets/1771026/12420191/6e65bdf8-bebb-11e5-9098-c28019437d86.png)

I've tried it with a `.php` file and a `.bat` file, the results were similar:
![php](https://cloud.githubusercontent.com/assets/1771026/12420190/6e61c66c-bebb-11e5-8f94-21c6e7efadab.png)
![bat](https://cloud.githubusercontent.com/assets/1771026/12420189/6e59a4c8-bebb-11e5-85bf-d19408b9145f.png)

The screenshots I made are from Linux, since I didn't have a Windows PC at my disposal at this moment.

**Comment by larpo1** [comment]
I have this issue too. linter-just-say-no is not installed

`/Users/me/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:527
Hide Stack Trace
TypeError: element.replace is not a function
    at Object.module.exports.parseStackClass (/Users/larpo/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:527:31)
    at Object.module.exports.getStackClasses (/Users/larpo/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:456:17)
    at Object.module.exports.getCalledClass (/Users/larpo/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:25:21)
    at Object.module.exports.getMemberContext (/Users/larpo/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:663:28)
    at PropertyProvider.module.exports.PropertyProvider.getTooltipForWord (/Users/larpo/.atom/packages/atom-autocomplete-php/lib/tooltip/property-provider.coffee:17:25)
    at PropertyProvider.module.exports.AbstractProvider.showPopoverFor (/Users/larpo/.atom/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:109:24)
    at HTMLSpanElement.<anonymous> (/Users/larpo/.atom/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:78:22)
    at HTMLDivElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)`

**Comment by roddypratt** [comment]
Not sure if reproducable but I had this today too.,

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package 0.25.6

### Stack Trace

Uncaught TypeError: marker.destroy is not a function

```
At C:\Users\roddy\AppData\Local\atom\app-1.18.0\resources\app\src\pane.js:1095

TypeError: marker.destroy is not a function
    at FunctionProvider.module.exports.AbstractProvider.removeAnnotations (/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:222:24)
    at FunctionProvider.module.exports.AbstractProvider.rescan (/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:240:10)
    at /packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:24:18
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.saveAs (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:1142:33)
    at TextBuffer.module.exports.TextBuffer.save (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:1108:25)
    at TextEditor.module.exports.TextEditor.save (~/AppData/Local/atom/app-1.18.0/resources/app/src/text-editor.js:925:32)
    at Pane.module.exports.Pane.saveItem (~/AppData/Local/atom/app-1.18.0/resources/app/src/pane.js:780:24)
    at Pane.saveItem (~/AppData/Local/atom/app-1.18.0/resources/app/src/pane.js:3:65)
    at Pane.module.exports.Pane.saveActiveItem (~/AppData/Local/atom/app-1.18.0/resources/app/src/pane.js:763:25)
    at Workspace.saveActivePaneItem (~/AppData/Local/atom/app-1.18.0/resources/app/src/workspace.js:1548:46)
    at atom-workspace.core:save (~/AppData/Local/atom/app-1.18.0/resources/app/src/register-default-commands.js:236:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:265:35)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.18.0/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -7:06.3.0 core:save (input.hidden-input)
     -6:55 intentions:highlight (input.hidden-input)
     -6:54.5.0 core:save (input.hidden-input)
  8x -6:47.5.0 intentions:highlight (input.hidden-input)
     -6:46.8.0 core:save (input.hidden-input)
     -5:19.2.0 core:move-up (input.hidden-input)
  3x -5:18.5.0 core:backspace (input.hidden-input)
  2x -3:54.6.0 editor:newline (input.hidden-input)
     -3:40.9.0 core:backspace (input.hidden-input)
     -3:40.3.0 intentions:highlight (input.hidden-input)
     -3:39.3.0 editor:newline (input.hidden-input)
     -3:38.7.0 core:move-up (input.hidden-input)
     -3:38.4.0 core:move-right (input.hidden-input)
  7x -3:36.2.0 core:backspace (input.hidden-input)
     -2:30.4.0 intentions:highlight (input.hidden-input)
     -2:30.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.2 
atom-typescript 11.0.3 
browser-plus 0.0.96 
build 0.68.0 
build-innosetup 0.6.2 
build-tsc 0.7.2 
busy 0.7.0 
busy-signal 1.4.3 
console-panel 0.2.1 
file-icons 2.1.7 
git-plus 7.9.3 
intentions 1.1.2 
language-ini 1.19.0 
language-innosetup 2.11.4 
language-nginx 0.8.0 
linter 2.2.0 
linter-jsonlint 1.3.0 
linter-php 1.3.2 
linter-tslint 1.6.0 
linter-ui-default 1.6.1 
open-on-bitbucket 0.4.0 
pigments 0.39.1 
platformio-ide-terminal 2.5.1 
todo-show 1.11.0 
xatom-debug 1.6.7 
xatom-debug-chrome 0.7.4 
xatom-debug-nodejs 0.9.3 
```

**Comment by konstantinj** [comment]
Got it also when saving an nginx.conf.

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package 0.25.6


### Stack Trace

Uncaught TypeError: marker.destroy is not a function

```
At /Applications/Atom.app/Contents/Resources/app/src/pane.js:1095

TypeError: marker.destroy is not a function
    at FunctionProvider.module.exports.AbstractProvider.removeAnnotations (/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:222:24)
    at FunctionProvider.module.exports.AbstractProvider.rescan (/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:240:10)
    at /packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:24:18
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1142:33)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1108:25)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:925:32)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:780:24)
    at Pane.saveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:3:65)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:763:25)
    at Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:1548:46)
    at atom-workspace.core:save (/Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:236:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.3 
atom-cform 0.6.0 
atom-cform-yaml 0.4.1 
autocomplete-json 5.5.0 
busy-signal 1.4.3 
color-picker 2.2.5 
docker 0.7.0 
file-icons 2.1.8 
fonts 3.0.2 
git-log 0.4.1 
git-plus 7.9.3 
git-time-machine 1.5.9 
intentions 1.1.2 
language-docker 1.1.8 
language-markdown 0.23.0 
language-nginx 0.8.0 
linter 2.2.0 
linter-docker 0.2.0 
linter-php 1.3.2 
linter-ui-default 1.6.2 
markdown-preview-plus 2.4.10 
minimap 4.28.2 
tree-view-git-status 1.4.0 
```

**Comment by kusmierczykw** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package 0.25.6


### Stack Trace

Uncaught TypeError: marker.destroy is not a function

```
At C:\Users\wojci\AppData\Local\atom\app-1.18.0\resources\app\src\pane.js:1095

TypeError: marker.destroy is not a function
    at FunctionProvider.module.exports.AbstractProvider.removeAnnotations (/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:222:24)
    at FunctionProvider.module.exports.AbstractProvider.rescan (/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:240:10)
    at /packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:24:18
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.saveAs (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:1142:33)
    at TextBuffer.module.exports.TextBuffer.save (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:1108:25)
    at TextEditor.module.exports.TextEditor.save (~/AppData/Local/atom/app-1.18.0/resources/app/src/text-editor.js:925:32)
    at Pane.module.exports.Pane.saveItem (~/AppData/Local/atom/app-1.18.0/resources/app/src/pane.js:780:24)
    at Pane.saveItem (~/AppData/Local/atom/app-1.18.0/resources/app/src/pane.js:3:65)
    at Pane.module.exports.Pane.saveActiveItem (~/AppData/Local/atom/app-1.18.0/resources/app/src/pane.js:763:25)
    at Workspace.saveActivePaneItem (~/AppData/Local/atom/app-1.18.0/resources/app/src/workspace.js:1548:46)
    at atom-workspace.core:save (~/AppData/Local/atom/app-1.18.0/resources/app/src/register-default-commands.js:236:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:265:35)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.18.0/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -1:08.8.0 core:cancel (input.hidden-input)
 11x -1:08.5.0 core:backspace (input.hidden-input)
     -1:06.9.0 intentions:highlight (input.hidden-input)
     -1:06.8.0 core:save (input.hidden-input)
     -1:05.7.0 intentions:highlight (input.hidden-input)
     -1:05.7.0 core:save (input.hidden-input)
     -1:04.3.0 intentions:highlight (input.hidden-input)
     -1:04.2.0 core:save (input.hidden-input)
  2x -0:30.4.0 core:backspace (input.hidden-input)
  2x -0:27.8.0 core:confirm (input.hidden-input)
     -0:14.1.0 intentions:highlight (input.hidden-input)
     -0:14 core:save (input.hidden-input)
     -0:12.5.0 intentions:highlight (input.hidden-input)
  5x -0:12.4.0 core:save (input.hidden-input)
     -0:09.1.0 intentions:highlight (input.hidden-input)
     -0:09.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
aligner-php 1.1.1 
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.4 
atom-live-server 2.1.2 
atom-ternjs 0.18.3 
atom-wordpress 0.3.0 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autocomplete 0.47.0 
autocomplete-php 0.3.7 
autocomplete-wordpress-hooks 0.2.2 
busy-signal 1.4.3 
emmet 2.4.3 
file-icons 2.1.8 
highlight-selected 0.13.1 
intentions 1.1.2 
linter 2.2.0 
linter-just-say-no 0.7.3 
linter-ui-default 1.6.2 
livereload 0.4.4 
minimap 4.28.3 
minimap-highlight-selected 4.6.1 
pigments 0.39.1 
project-manager 3.3.5 
todo-show 1.11.0 
wordpress 0.2.0 
wordpress-api 1.2.2 
wordpress-dictionary 4.4.0 
wordpress-suite 1.1.1 
wp-dev 0.3.5 
```
