### ISSUE TITLE
Uncaught TypeError: Cannot read property '$(".art-slider-inner", slideContainer)' of undefined

### ISSUE THREAD

**Issue by sirmaximuz** [Peekmo/atom-autocomplete-php#225]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Debian GNU/Linux
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.18.7

### Stack Trace

Uncaught TypeError: Cannot read property '$(".art-slider-inner", slideContainer)' of undefined

```
At /home/prienro/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:689

TypeError: Cannot read property '$(".art-slider-inner", slideContainer)' of undefined
    at Object.module.exports.getMemberContext (/home/prienro/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:689:32)
    at FunctionProvider.module.exports.FunctionProvider.getTooltipForWord (/home/prienro/.atom/packages/atom-autocomplete-php/lib/tooltip/function-provider.coffee:18:25)
    at FunctionProvider.module.exports.AbstractProvider.showPopoverFor (/home/prienro/.atom/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:109:24)
    at HTMLSpanElement.<anonymous> (/home/prienro/.atom/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:78:22)
    at HTMLDivElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -4:23.5.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:23.5.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -4:10 core:move-right (atom-text-editor.editor.is-focused)
     -4:08.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:07.5.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -4:07.5.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -3:53.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:52.5.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
 19x -3:50.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:40.2.0 core:paste (atom-text-editor.editor.is-focused)
     -3:38.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -3:35.7.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -3:33.6.0 core:save (atom-text-editor.editor.is-focused)
     -2:59.7.0 tree-view:copy (span.name.icon.icon-file-directory)
     -2:52.8.0 tree-view:paste (span.name.icon.icon-file-directory)
     -1:33.5.0 core:save (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-autocomplete-php"
    ]
  },
  "atom-autocomplete-php": {}
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.7.15
php-integrator-base, v0.4.7
remote-edit, v1.8.23

# Dev
No dev packages
```

**Comment by Peekmo** [comment]
Hello,

It should be fixed now,

Regards,
Peekmo
