### ISSUE TITLE
Uncaught TypeError: Cannot read property 'class' of undefined

### ISSUE THREAD

**Issue by ThoyibH07** [Peekmo/atom-autocomplete-php#226]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.2
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.18.7

### Stack Trace

Uncaught TypeError: Cannot read property 'class' of undefined

```
At /Users/diposmacbookpro/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:755

TypeError: Cannot read property 'class' of undefined
    at Object.module.exports.parseElements (/Users/diposmacbookpro/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:755:24)
    at Object.module.exports.getCalledClass (/Users/diposmacbookpro/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:30:17)
    at Object.module.exports.getMemberContext (/Users/diposmacbookpro/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:661:28)
    at FunctionProvider.module.exports.FunctionProvider.getTooltipForWord (/Users/diposmacbookpro/.atom/packages/atom-autocomplete-php/lib/tooltip/function-provider.coffee:18:25)
    at FunctionProvider.module.exports.AbstractProvider.showPopoverFor (/Users/diposmacbookpro/.atom/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:109:24)
    at HTMLSpanElement.<anonymous> (/Users/diposmacbookpro/.atom/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:78:22)
    at HTMLDivElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -1:03.9.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {},
  "atom-autocomplete-php": {
    "insertNewlinesForUseStatements": true
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.7
language-blade, v0.19.0
laravel, v0.7.0
php-cs-fixer, v2.5.2

# Dev
No dev packages
```

**Comment by benyanke** [comment]
This occurs to me when I drag tabs between atom windows.
