### ISSUE TITLE
Uncaught TypeError: Cannot read property 'render' of undefined

### ISSUE THREAD

**Issue by fabiocicerchia** [Peekmo/atom-autocomplete-php#228]
It just appeared while I was closing some tabs with opened PHP files.

**Atom Version**: 1.4.0
**System**: Ubuntu 15.04
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.18.7

### Stack Trace

Uncaught TypeError: Cannot read property 'render' of undefined

```
At /home/fabio/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:689

TypeError: Cannot read property 'render' of undefined
    at Object.module.exports.getMemberContext (/home/fabio/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:689:32)
    at FunctionProvider.module.exports.FunctionProvider.getTooltipForWord (/home/fabio/.atom/packages/atom-autocomplete-php/lib/tooltip/function-provider.coffee:18:25)
    at FunctionProvider.module.exports.AbstractProvider.showPopoverFor (/home/fabio/.atom/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:109:24)
    at HTMLSpanElement.<anonymous> (/home/fabio/.atom/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:78:22)
    at HTMLDivElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -1:06.4.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  4x -1:05.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:02.6.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:02.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -1:01.1.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:53.3.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
  8x -0:52.7.0 core:move-left (atom-text-editor.editor.is-focused)
  3x -0:50.9.0 core:select-left (atom-text-editor.editor.is-focused)
 10x -0:49.2.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:43.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:42.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:41.3.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:36.9.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:33.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:31.9.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:20.6.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.7
file-icons, v1.6.14
wakatime, v5.0.2

# Dev
No dev packages
```

**Comment by Peekmo** [comment]
Hello,

It should be fixed now,

Regards,
Peekmo
