### ISSUE TITLE
Uncaught Error: Unable to find composer.json file or to open it.

### ISSUE THREAD

**Issue by abhirajm** [Peekmo/atom-autocomplete-php#23]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.1.4

### Stack Trace

Uncaught Error: Unable to find composer.json file or to open it.

```
At /Users/abhiraj/.atom/packages/atom-autocomplete-php/lib/services/php-proxy.coffee:77

Error: Unable to find composer.json file or to open it.
  at readComposer (/Users/abhiraj/.atom/packages/atom-autocomplete-php/lib/services/php-proxy.coffee:77:13)
  at Object.module.exports.composer (/Users/abhiraj/.atom/packages/atom-autocomplete-php/lib/services/php-proxy.coffee:114:12)
  at Object.module.exports.createNamespace (/Users/abhiraj/.atom/packages/atom-autocomplete-php/lib/services/namespace.coffee:13:25)
  at atom-workspace.atom.commands.add.atom-autocomplete-php:namespace (/Users/abhiraj/.atom/packages/atom-autocomplete-php/lib/config.coffee:43:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)

```

### Commands

```
     -2:39.8.0 core:move-up (atom-text-editor.editor.is-focused)
     -2:39.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:39.1.0 core:move-up (atom-text-editor.editor.is-focused)
     -2:38.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:15.2.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:15.2.0 editor:newline (atom-text-editor.editor.is-focused)
  4x -0:30 core:backspace (atom-text-editor.editor.is-focused)
     -0:28.7.0 application:new-file (atom-text-editor.editor.is-focused)
     -0:26.1.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:26.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:25.9.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:25.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:24.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:09.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:08.1.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:02.3.0 atom-autocomplete-php:namespace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "autocomplete-plus"
    ]
  },
  "atom-autocomplete-php": {}
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.1.4
autoclose-html, v0.18.0
autocomplete-php, v0.3.6
emmet, v2.3.10
jshint, v1.3.8
project-manager, v1.15.10

# Dev
No dev packages
```

**Comment by Peekmo** [comment]
Hello,

Thank you for the report, I'll try to properly handle this error. But note that to avoid it, you have to open a project managed with composer. (The composer.json must be in the root opened folder)

**Comment by Peekmo** [comment]
Hello,

The error was trigger by my code. Now an alert is send instead of an error.

Regards,
Peekmo

**Comment by rodrigobertin** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Unknown Windows Version
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.13.7


### Stack Trace

Uncaught Error

```
At /C:/Users/Rodrigo/.atom/packages/atom-autocomplete-php/lib/services/php-proxy.coffee:126

undefined
```

### Commands

```
     -0:09.4.0 atom-autocomplete-php:namespace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ],
    "packagesWithKeymapsDisabled": []
  },
  "atom-autocomplete-php": {
    "binPhp": "C:\\xampp\\php\\php.exe"
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.2
angularjs-snippets, v0.10.18
atom-autocomplete-php, v0.13.7
atom-bootstrap4, v1.2.11
auto-id-class, v0.2.6
autocomplete-ionic-framework, v0.2.1
autocomplete-jquery-mobile, v0.2.2
autocomplete-modules, v1.3.0
autocomplete-php, v0.3.7
bootstrap-3-snippetset, v0.0.6
bootstrap3-snippets, v0.1.2
bottom-dock, v0.3.5
build-gulp, v0.2.0
color-picker, v2.0.13
css-snippets, v0.9.0
emmet, v2.3.13
emmet-snippets-compatibility, v1.0.0
file-icons, v1.6.10
gulp-manager, v0.2.10
gulp-snippets, v0.6.2
icon-fonts, v1.7.1
jquery-snippets, v11.0.0
language-apache, v1.3.0
language-sql-mysql, v0.3.1
linter, v1.8.1
linter-php, v1.0.5
local-history, v3.2.3
php-analyser, v0.2.0
php-composer-completion, v0.3.4
php-cs-fixer, v2.5.0
simple-drag-drop-text, v0.3.0
terminal-plus, v0.8.2
todo-manager, v0.2.5

# Dev
No dev packages
```
