### ISSUE TITLE
Uncaught TypeError: Cannot read property 'configure' of undefined

### ISSUE THREAD

**Issue by xylesoft** [Peekmo/atom-autocomplete-php#235]
[Enter steps to reproduce below:]

1. click in a PHP Code pane
2. added { and then saved

**Atom Version**: 1.5.3
**System**: Mac OS X 10.10.5
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.18.7

### Stack Trace

Uncaught TypeError: Cannot read property 'configure' of undefined

```
At /opt/homebrew-cask/Caskroom/atom/1.4.1/Atom.app/Contents/Resources/app.asar/src/pane.js:825

TypeError: Cannot read property 'configure' of undefined
    at Object.module.exports.getMemberContext (/Users/xxxxxxxx/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:689:32)
    at FunctionProvider.module.exports.FunctionProvider.extractAnnotationInfo (/Users/xxxxxxxx/.atom/packages/atom-autocomplete-php/lib/annotation/method-provider.coffee:17:27)
    at FunctionProvider.module.exports.AbstractProvider.placeAnnotation (/Users/xxxxxxxx/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:103:27)
    at FunctionProvider.<anonymous> (/Users/xxxxxxxx/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:92:18)
    at FunctionProvider.module.exports.AbstractProvider.registerAnnotations (/Users/xxxxxxxx/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:91:13)
    at FunctionProvider.module.exports.AbstractProvider.rescan (/Users/xxxxxxxx/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:236:10)
    at /Users/xxxxxxxx/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:24:18
    at Function.module.exports.Emitter.simpleDispatch (/opt/homebrew-cask/Caskroom/atom/1.4.1/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.4.1/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/opt/homebrew-cask/Caskroom/atom/1.4.1/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1067:27)
    at TextBuffer.module.exports.TextBuffer.save (/opt/homebrew-cask/Caskroom/atom/1.4.1/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1037:19)
    at TextEditor.module.exports.TextEditor.save (/opt/homebrew-cask/Caskroom/atom/1.4.1/Atom.app/Contents/Resources/app.asar/src/text-editor.js:630:26)
    at Pane.module.exports.Pane.saveItem (/opt/homebrew-cask/Caskroom/atom/1.4.1/Atom.app/Contents/Resources/app.asar/src/pane.js:545:18)
    at Pane.module.exports.Pane.saveActiveItem (/opt/homebrew-cask/Caskroom/atom/1.4.1/Atom.app/Contents/Resources/app.asar/src/pane.js:528:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/opt/homebrew-cask/Caskroom/atom/1.4.1/Atom.app/Contents/Resources/app.asar/src/workspace.js:649:35)
    at atom-workspace.commandRegistry.add.core:save (/opt/homebrew-cask/Caskroom/atom/1.4.1/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.4.1/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /opt/homebrew-cask/Caskroom/atom/1.4.1/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.4.1/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/1.4.1/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/opt/homebrew-cask/Caskroom/atom/1.4.1/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.4.1/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -3:53.2.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -3:52.4.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -3:52 core:move-left (atom-text-editor.editor.is-focused)
     -3:51.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:49.9.0 bracket-matcher:remove-matching-brackets (atom-text-editor.editor.is-focused)
     -3:49.1.0 editor:newline (atom-text-editor.editor.is-focused)
  8x -3:47.8.0 core:delete (atom-text-editor.editor.is-focused)
  2x -3:44.2.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:42.8.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused)
  4x -3:42.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:39.5.0 editor:move-to-end-of-line (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -3:38.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:04.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:04.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:04.2.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:03.8.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "hyperclick-php"
    ]
  },
  "atom-autocomplete-php": {
    "binComposer": "/Users/xxxxxxxx/usr/bin/composer",
    "binPhp": "/usr/local/bin/php"
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.7
php-cs-fixer, v2.5.6
php-debug, v0.2.1
php-integrator-annotations, v0.2.3
php-integrator-tooltips, v0.3.1

# Dev
No dev packages
```

**Comment by Peekmo** [comment]
Hello,

It should be fixed now,

Regards,
Peekmo
