### ISSUE TITLE
Uncaught TypeError: Cannot read property 'renderLabel' of undefined

### ISSUE THREAD

**Issue by danmic94** [Peekmo/atom-autocomplete-php#236]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Microsoft Windows 10 Pro
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.18.7

### Stack Trace

Uncaught TypeError: Cannot read property 'renderLabel' of undefined

```
At /C:/Users/micda/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:619

TypeError: Cannot read property 'renderLabel' of undefined
    at Object.module.exports.getMemberContext (file:///C:/Users/micda/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:689:32)
    at FunctionProvider.module.exports.FunctionProvider.getTooltipForWord (file:///C:/Users/micda/.atom/packages/atom-autocomplete-php/lib/tooltip/function-provider.coffee:18:25)
    at FunctionProvider.module.exports.AbstractProvider.showPopoverFor (file:///C:/Users/micda/.atom/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:109:24)
    at HTMLSpanElement.<anonymous> (file:///C:/Users/micda/.atom/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:78:22)
    at HTMLDivElement.jQuery.event.dispatch (C:\Users\micda\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (C:\Users\micda\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

### Commands

```
  3x -6:40.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:32 editor:newline (atom-text-editor.editor.is-focused)
  4x -6:29.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:21.7.0 core:save (atom-text-editor.editor.is-focused)
  4x -6:07.2.0 core:backspace (atom-text-editor.editor.is-focused)
 11x -6:00.4.0 core:undo (atom-text-editor.editor.is-focused)
 14x -5:49.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:58.2.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:52.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:48.6.0 core:undo (atom-text-editor.editor.is-focused)
  3x -0:46.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:43.3.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:07.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:05.7.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.7
autoclose-html, v0.20.0
autocomplete-html-entities, v0.1.0
file-icons, v1.6.14
html-id-class-snippets, v1.4.1
Zen, v0.16.3

# Dev
No dev packages
```

**Comment by Peekmo** [comment]
Hello,

It should be fixed now,

Regards,
Peekmo
