### ISSUE TITLE
Uncaught TypeError: editor.gutterWithName is not a function

### ISSUE THREAD

**Issue by NeZaMy** [Peekmo/atom-autocomplete-php#239]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.18.7

### Stack Trace

Uncaught TypeError: editor.gutterWithName is not a function

```
At /C:/Users/Mahmoud/.atom/packages/php-debug/lib/php-debug.coffee:549

TypeError: editor.gutterWithName is not a function
    at Object.module.exports.PhpDebug.createGutter (file:///C:/Users/Mahmoud/.atom/packages/php-debug/lib/php-debug.coffee:309:16)
    at Object.module.exports.PhpDebug.toggleDebugging (file:///C:/Users/Mahmoud/.atom/packages/php-debug/lib/php-debug.coffee:347:8)
    at PhpDebugStatusView.module.exports.PhpDebugStatusView.toggleDebugging (file:///C:/Users/Mahmoud/.atom/packages/php-debug/lib/status/php-debug-status-view.coffee:14:15)
    at space-pen-div.<anonymous> (D:\Programs\Portable\Atom\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:231:38)
    at space-pen-div.jQuery.event.dispatch (D:\Programs\Portable\Atom\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at space-pen-div.elemData.handle (D:\Programs\Portable\Atom\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

### Commands

```
     -7:15.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.7
autocomplete-php, v0.3.7
php-composer-completion, v0.3.4
php-debug, v0.2.2
php-integrator-call-tips, v0.2.1
php-integrator-refactoring, v0.3.0

# Dev
No dev packages
```

**Comment by Peekmo** [comment]
Hello, there's an incompatibility with php-debug.

See https://github.com/Peekmo/atom-autocomplete-php/issues/229

**Comment by did-vmonroig** [comment]
Can anyone recommend any other extension as a replacement for php-debug?
