### ISSUE TITLE
Uncaught TypeError: Cannot read property 'autocomplete' of null

### ISSUE THREAD

**Issue by meigallodixital** [Peekmo/atom-autocomplete-php#24]
1. On new class creation extending other class

**Atom Version**: 1.0.0
**System**: Windows 7
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.1.7

### Stack Trace

Uncaught TypeError: Cannot read property 'autocomplete' of null

```
At C:\Users\ggonzalezdominguez\.atom\packages\atom-autocomplete-php\lib\providers\class-provider.coffee:27

TypeError: Cannot read property 'autocomplete' of null
  at ClassProvider.module.exports.ClassProvider.fetchSuggestions (C:\Users\ggonzalezdominguez\.atom\packages\atom-autocomplete-php\lib\providers\class-provider.coffee:27:19)
  at ClassProvider.module.exports.AbstractProvider.getSuggestions (C:\Users\ggonzalezdominguez\.atom\packages\atom-autocomplete-php\lib\providers\abstract-provider.coffee:23:13)
  at C:\Users\ggonzalezdominguez\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:255:56
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (C:\Users\ggonzalezdominguez\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:234:17)
  at AutocompleteManager.getSuggestionsFromProviders (C:\Users\ggonzalezdominguez\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3:61)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (C:\Users\ggonzalezdominguez\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:221:19)
  at C:\Users\ggonzalezdominguez\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3:61

```

### Commands

```
  2x -4:07.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:05.4.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -4:04.6.0 core:save (atom-text-editor.editor.is-focused)
     -3:40.1.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -3:23.2.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -3:23.2.0 snippets:expand (atom-text-editor.editor.is-focused)
     -3:23.2.0 editor:indent (atom-text-editor.editor.is-focused)
     -3:22.9.0 core:save (atom-text-editor.editor.is-focused)
     -2:22.6.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -2:20.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:19.2.0 project-find:show (atom-text-editor.editor.mini.is-focused)
     -2:17.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:23 project-find:show (atom-text-editor.editor.is-focused)
     -0:22 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:15.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:12.9.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "atom-autocomplete-php": {
    "binPhp": "D:\\php\\php.exe",
    "binComposer": "C:\\ProgramData\\ComposerSetup\\bin\\composer"
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.1.7
atom-beautify, v0.28.7
line-ending-converter, v1.2.0
linter, v1.1.0
linter-jshint, v0.1.7
linter-php, v0.0.15
linter-phpcs, v0.0.15
linter-phpmd, v0.0.11
live-archive, v0.1.15
minimap, v4.10.1
minimap-git-diff, v4.1.3
minimap-linter, v1.0.0
php-twig, v4.0.0
remote-sync, v3.1.2
symfony-snippets, v0.3.0

# Dev
No dev packages
```

**Comment by Peekmo** [comment]
Hello,

I get it today too. It's not related to extends only, I'll look where is the problem.
Thank you for the report

**Comment by Peekmo** [comment]
The problem should not come again.

It seems that the class index is corrupted sometimes ? Why, I don't know. With this fix the entire index is rebuild if something is wrong.
