### ISSUE TITLE
Uncaught TypeError: editor.getPath is not a function

### ISSUE THREAD

**Issue by robertobermejo** [Peekmo/atom-autocomplete-php#246]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.2
**System**: Mac OS X 10.11.4
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.18.7

### Stack Trace

Uncaught TypeError: editor.getPath is not a function

```
At /Users/rbermejo/.atom/packages/atom-autocomplete-php/lib/services/namespace.coffee:29

TypeError: editor.getPath is not a function
    at Object.module.exports.createNamespace (/Users/rbermejo/.atom/packages/atom-autocomplete-php/lib/services/namespace.coffee:29:23)
    at atom-workspace.atom.commands.add.atom-autocomplete-php:namespace (/Users/rbermejo/.atom/packages/atom-autocomplete-php/lib/config.coffee:98:23)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:47.1.0 settings-view:open (atom-pane.pane.active)
     -0:40.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -0:13.6.0 core:confirm (atom-text-editor#atom-autocomplete-php.binComposer.editor.mini.is-focused)
  2x -0:07.9.0 core:save (atom-text-editor#atom-autocomplete-php.binComposer.editor.mini.is-focused)
     -0:01.9.0 atom-autocomplete-php:namespace (atom-text-editor#atom-autocomplete-php.binComposer.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "atom-autocomplete-php": {
    "binPhp": "/usr/bin/php"
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.7
atom-html-preview, v0.1.19
atom-jinja2, v0.5.0
atom-mocha, v0.0.4
atom-symfony2, v0.2.1
emmet, v2.4.3
language-ansi, v1.1.1
language-ansible, v0.1.3
language-babel, v2.17.1
language-twig, v1.6.3
linter, v1.11.4
linter-eslint, v7.2.0
linter-twig, v0.1.1
minimap, v4.21.0
npm, v0.1.0
php-integrator-annotations, v0.4.0
php-integrator-autocomplete-plus, v0.7.0
php-integrator-base, v0.8.0
php-integrator-call-tips, v0.2.3
php-integrator-linter, v0.2.2
php-integrator-navigation, v0.6.2
php-integrator-refactoring, v0.4.2
php-integrator-symbol-viewer, v0.5.6
php-integrator-tooltips, v0.6.0
php-twig, v4.0.0

# Dev
No dev packages
```

**Comment by Peekmo** [comment]
Hello,

Do you have more informations about how it happened ? That's really weird. Can you reproduce it ?

Regards,
Peekmo

**Comment by jeffdupont** [comment]
I got the same issue. I used the shift+cmd+P and then selected the "Atom Autocomplete PHP: Namespace"
