### ISSUE TITLE
Uncaught TypeError: Cannot read property 'first' of undefined

### ISSUE THREAD

**Issue by wleonid** [Peekmo/atom-autocomplete-php#247]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.2
**System**: Unknown Windows Version
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.18.7

### Stack Trace

Uncaught TypeError: Cannot read property 'first' of undefined

```
At C:\Users\Administrator\AppData\Local\atom\app-1.6.2\resources\app.asar\src\pane.js:896

TypeError: Cannot read property 'first' of undefined
    at Object.module.exports.getMemberContext (file:///C:/Users/Administrator/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:689:32)
    at FunctionProvider.module.exports.FunctionProvider.extractAnnotationInfo (file:///C:/Users/Administrator/.atom/packages/atom-autocomplete-php/lib/annotation/property-provider.coffee:17:27)
    at FunctionProvider.module.exports.AbstractProvider.placeAnnotation (file:///C:/Users/Administrator/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:103:27)
    at FunctionProvider.<anonymous> (file:///C:/Users/Administrator/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:92:18)
    at FunctionProvider.module.exports.AbstractProvider.registerAnnotations (file:///C:/Users/Administrator/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:91:13)
    at FunctionProvider.module.exports.AbstractProvider.rescan (file:///C:/Users/Administrator/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:236:10)
    at file:///C:/Users/Administrator/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:24:18
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Administrator\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Administrator\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\Administrator\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1073:27)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\Administrator\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1043:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\Administrator\AppData\Local\atom\app-1.6.2\resources\app.asar\src\text-editor.js:629:26)
    at Pane.module.exports.Pane.saveItem (C:\Users\Administrator\AppData\Local\atom\app-1.6.2\resources\app.asar\src\pane.js:613:18)
    at Pane.module.exports.Pane.saveItems (C:\Users\Administrator\AppData\Local\atom\app-1.6.2\resources\app.asar\src\pane.js:652:16)
    at PaneContainer.module.exports.PaneContainer.saveAll (C:\Users\Administrator\AppData\Local\atom\app-1.6.2\resources\app.asar\src\pane-container.js:222:14)
    at Workspace.module.exports.Workspace.saveAll (C:\Users\Administrator\AppData\Local\atom\app-1.6.2\resources\app.asar\src\workspace.js:665:33)
    at atom-workspace.commandRegistry.add.window:save-all (C:\Users\Administrator\AppData\Local\atom\app-1.6.2\resources\app.asar\src\register-default-commands.js:187:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Administrator\AppData\Local\atom\app-1.6.2\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\Administrator\AppData\Local\atom\app-1.6.2\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Administrator\AppData\Local\atom\app-1.6.2\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\Administrator\AppData\Local\atom\app-1.6.2\resources\app.asar\src\atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
  2x -2:30.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:27.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:27.4.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -2:27.4.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -2:27.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:25.1.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -2:25.1.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
  9x -2:07.0 pane:show-previous-item (atom-text-editor.editor.is-focused)
  2x -1:51.7.0 core:save-as (atom-text-editor.editor.is-focused)
     -0:57.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  3x -0:47.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:44.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:44.4.0 window:save-all (atom-text-editor.editor)
  2x -0:34.7.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:31.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:10.3.0 window:save-all (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.7
atom-beautify, v0.29.2
autocomplete-json, v1.9.1
css-snippets, v0.9.0
docblockr, v0.7.3
emmet, v2.4.3
file-icons, v1.7.1
git-plus, v5.13.4
language-asciidoc, v0.12.0
minimap, v4.21.0
php-cs-fixer, v2.5.6
simplified-chinese-menu, v3.4.11

# Dev
No dev packages
```

**Comment by Peekmo** [comment]
Hello,

It should be fixed now,

Regards,
Peekmo
