### ISSUE TITLE
Cannot read property 'indexAction' of undefined

### ISSUE THREAD

**Issue by theragekevin** [Peekmo/atom-autocomplete-php#248]
Hello,

since few days i get some error messages with the package. Here is one of them.

Stack Trace:
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.2
**System**: Unknown Windows Version
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.18.7

### Stack Trace

Failed to activate the atom-autocomplete-php package

```
At Cannot read property 'indexAction' of undefined

TypeError: Cannot read property 'indexAction' of undefined
    at Object.module.exports.getMemberContext (file:///C:/Users/KevinT/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:689:32)
    at FunctionProvider.module.exports.FunctionProvider.extractAnnotationInfo (file:///C:/Users/KevinT/.atom/packages/atom-autocomplete-php/lib/annotation/method-provider.coffee:17:27)
    at FunctionProvider.module.exports.AbstractProvider.placeAnnotation (file:///C:/Users/KevinT/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:103:27)
    at FunctionProvider.<anonymous> (file:///C:/Users/KevinT/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:92:18)
    at FunctionProvider.module.exports.AbstractProvider.registerAnnotations (file:///C:/Users/KevinT/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:91:13)
    at file:///C:/Users/KevinT/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:26:14
    at Workspace.module.exports.Workspace.observeTextEditors (C:\Users\KevinT\AppData\Local\atom\app-1.6.2\resources\app.asar\src\workspace.js:302:9)
    at FunctionProvider.module.exports.AbstractProvider.init (file:///C:/Users/KevinT/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:22:24)
    at AnnotationManager.module.exports.AnnotationManager.init (file:///C:/Users/KevinT/.atom/packages/atom-autocomplete-php/lib/annotation/annotation-manager.coffee:17:22)
    at Object.module.exports.activate (file:///C:/Users/KevinT/.atom/packages/atom-autocomplete-php/lib/peekmo-php-atom-autocomplete.coffee:75:28)
    at Package.module.exports.Package.activateNow (C:\Users\KevinT\AppData\Local\atom\app-1.6.2\resources\app.asar\src\package.js:181:20)
    at C:\Users\KevinT\AppData\Local\atom\app-1.6.2\resources\app.asar\src\package.js:155:32
    at Package.module.exports.Package.measure (C:\Users\KevinT\AppData\Local\atom\app-1.6.2\resources\app.asar\src\package.js:92:15)
    at C:\Users\KevinT\AppData\Local\atom\app-1.6.2\resources\app.asar\src\package.js:148:26
    at Package.module.exports.Package.activate (C:\Users\KevinT\AppData\Local\atom\app-1.6.2\resources\app.asar\src\package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\KevinT\AppData\Local\atom\app-1.6.2\resources\app.asar\src\package-manager.js:526:21)
    at C:\Users\KevinT\AppData\Local\atom\app-1.6.2\resources\app.asar\src\package-manager.js:338:19
    at C:\Users\KevinT\AppData\Local\atom\app-1.6.2\resources\app.asar\src\config.js:631:20
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\KevinT\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\KevinT\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Config.module.exports.Config.emitChangeEvent (C:\Users\KevinT\AppData\Local\atom\app-1.6.2\resources\app.asar\src\config.js:816:29)
    at Config.module.exports.Config.setRawValue (C:\Users\KevinT\AppData\Local\atom\app-1.6.2\resources\app.asar\src\config.js:608:19)
    at Config.module.exports.Config.set (C:\Users\KevinT\AppData\Local\atom\app-1.6.2\resources\app.asar\src\config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (C:\Users\KevinT\AppData\Local\atom\app-1.6.2\resources\app.asar\src\config.js:377:12)
    at Package.module.exports.Package.enable (C:\Users\KevinT\AppData\Local\atom\app-1.6.2\resources\app.asar\src\package.js:77:26)
    at PackageManager.module.exports.PackageManager.enablePackage (C:\Users\KevinT\AppData\Local\atom\app-1.6.2\resources\app.asar\src\package-manager.js:165:14)
    at HTMLButtonElement.<anonymous> (C:\Users\KevinT\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\settings-view\lib\package-card.js:314:27)
    at HTMLButtonElement.jQuery.event.dispatch (C:\Users\KevinT\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (C:\Users\KevinT\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-beautify"
    ],
    "projectHome": "C:\\wamp\\www\\"
  },
  "atom-autocomplete-php": {
    "binComposer": "C:\\ProgramData\\ComposerSetup\\bin\\composer.phar",
    "binPhp": "C:\\wamp\\bin\\php\\php5.5.12\\php.exe"
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.7
atom-symfony2, v0.2.1
docblockr, v0.7.3
minimap, v4.21.0
php-cs-fixer, v2.5.6
php-twig, v4.0.0

# Dev
No dev packages
```

**Comment by Peekmo** [comment]
Hello,

It should be fixed now,

Regards,
Peekmo
