### ISSUE TITLE
Uncaught TypeError: Cannot read property 'pegarResultados' of undefined

### ISSUE THREAD

**Issue by masterzd** [Peekmo/atom-autocomplete-php#251]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Unknown Windows Version
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.18.7

### Stack Trace

Uncaught TypeError: Cannot read property 'pegarResultados' of undefined

```
At /C:/Users/henrique.souza/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:619

TypeError: Cannot read property 'pegarResultados' of undefined
    at Object.module.exports.getMemberContext (file:///C:/Users/henrique.souza/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:689:32)
    at FunctionProvider.module.exports.FunctionProvider.getTooltipForWord (file:///C:/Users/henrique.souza/.atom/packages/atom-autocomplete-php/lib/tooltip/function-provider.coffee:18:25)
    at FunctionProvider.module.exports.AbstractProvider.showPopoverFor (file:///C:/Users/henrique.souza/.atom/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:109:24)
    at HTMLSpanElement.<anonymous> (file:///C:/Users/henrique.souza/.atom/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:78:22)
    at HTMLDivElement.jQuery.event.dispatch (C:\Users\henrique.souza\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (C:\Users\henrique.souza\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

### Commands

```
  3x -9:35.7.0 core:undo (atom-text-editor.editor.is-focused)
     -8:42.1.0 core:delete (atom-text-editor.editor.is-focused)
  2x -8:41.5.0 core:move-up (atom-text-editor.editor.is-focused)
  8x -8:41 core:move-right (atom-text-editor.editor.is-focused)
  9x -8:39.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -8:26.6.0 core:save (atom-text-editor.editor.is-focused)
     -8:08.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -8:05.5.0 core:save (atom-text-editor.editor.is-focused)
     -7:51.1.0 core:delete (atom-text-editor.editor.is-focused)
     -7:47.3.0 core:undo (atom-text-editor.editor.is-focused)
     -7:42.3.0 core:delete (atom-text-editor.editor.is-focused)
     -7:40.6.0 core:save (atom-text-editor.editor.is-focused)
  2x -3:34.6.0 core:move-right (atom-text-editor.editor.is-focused)
     -3:32.7.0 core:save (atom-text-editor.editor.is-focused)
  6x -0:48.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:45.6.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-php"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.7
git-control, v0.7.1
language-sql-mysql, v0.3.1

# Dev
No dev packages
```

**Comment by Peekmo** [comment]
Hello,

It should be fixed now,

Regards,
Peekmo
