### ISSUE TITLE
Just a bug on update Error deactivating package 'atom-autocomplete-php' 

### ISSUE THREAD

**Issue by turigeza** [Peekmo/atom-autocomplete-php#263]
```
Error deactivating package 'atom-autocomplete-php' TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
    at TypeError (native)
    at ClassProvider.module.exports.AbstractProvider.deactivate (/Users/geza/.atom/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:48:18)
    at TooltipManager.module.exports.TooltipManager.deactivate (/Users/geza/.atom/packages/atom-autocomplete-php/lib/tooltip/tooltip-manager.coffee:26:22)
    at Object.module.exports.deactivate (/Users/geza/.atom/packages/atom-autocomplete-php/lib/peekmo-php-atom-autocomplete.coffee:81:25)
    at Package.module.exports.Package.deactivate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:641:21)
    at PackageManager.module.exports.PackageManager.deactivatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:622:12)
    at PackageManager.module.exports.PackageManager.update (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:366:23)
    at PackageCard.module.exports.PackageCard.update (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:705:34)
    at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/updates-panel.js:75:112)
    at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
module.exports.Package.deactivate	@	/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:652
module.exports.PackageManager.deactivatePackage	@	/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:622
module.exports.PackageManager.update	@	/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:366
module.exports.PackageCard.update	@	/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:705
(anonymous function)	@	/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/updates-panel.js:75
jQuery.event.dispatch	@	/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435
elemData.handle	@	/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121

```

**Comment by Arcanemagus** [comment]
Any reason this was closed? This error is thrown any time this package is deactivated and is still present on v0.19.4.

**Comment by Arcanemagus** [comment]
It looks like this could be either in [popover.coffee](https://github.com/Peekmo/atom-autocomplete-php/blob/v0.19.4/lib/services/popover.coffee#L27) or [abstract-provider](https://github.com/Peekmo/atom-autocomplete-php/blob/v0.19.4/lib/tooltip/abstract-provider.coffee#L48).
