### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tags' of undefined

### ISSUE THREAD

**Issue by seanmars** [Peekmo/atom-autocomplete-php#270]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Unknown Windows Version
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.18.9

### Stack Trace

Uncaught TypeError: Cannot read property 'tags' of undefined

```
At /C:/Users/Mars/.atom/packages/symbols-tree-view/lib/symbols-tree-view.coffee:142

TypeError: Cannot read property 'tags' of undefined
    at SymbolsTreeView.<anonymous> (file:///C:/Users/Mars/.atom/packages/symbols-tree-view/lib/symbols-tree-view.coffee:83:17)
    at SymbolsTreeView.module.exports.SymbolsTreeView.focusClickedTag (file:///C:/Users/Mars/.atom/packages/symbols-tree-view/lib/symbols-tree-view.coffee:83:17)
    at Object.callback (file:///C:/Users/Mars/.atom/packages/symbols-tree-view/lib/main.coffee:65:9)
    at HyperclickForTextEditor._confirmSuggestion (C:\Users\Mars\.atom\packages\hyperclick\lib\HyperclickForTextEditor.js:111:20)
    at HyperclickForTextEditor._onMouseDown (C:\Users\Mars\.atom\packages\hyperclick\lib\HyperclickForTextEditor.js:166:14)
```

### Commands

```
     -3:42.5.0 tree-view:show-in-file-manager (span.name.icon.icon-file-text)
 32x -2:20.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:03.1.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
 38x -2:00.7.0 core:backspace (atom-text-editor.editor.is-focused)
 16x -1:17.5.0 core:move-left (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:13.9.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -1:13.6.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:10.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -1:02.8.0 core:save (atom-text-editor.editor.is-focused.hyperclick)
 27x -1:02.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:01.8.0 core:move-right (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "visual-studio-dark-syntax"
    ]
  },
  "atom-autocomplete-php": {
    "binComposer": "C:\\ProgramData\\ComposerSetup\\bin\\composer"
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.9
atom-beautify, v0.29.9
atom-jade, v0.3.0
atom-ternjs, v0.14.2
autoclose-html, v0.23.0
browser-plus, v0.0.60
color-picker, v2.1.1
cursor-history, v0.5.9
docblockr, v0.7.3
double-tag, v0.2.0
file-icons, v1.7.15
highlight-selected, v0.11.2
hyperclick, v0.0.36
jade-beautify, v0.1.4
jquery-snippets, v11.0.0
js-hyperclick, v1.4.2
jshint, v1.8.5
language-blade, v0.25.3
language-docker, v1.1.6
laravel, v0.7.0
last-cursor-position, v0.9.0
linter, v1.11.14
linter-csslint, v1.3.2
linter-docker, v0.1.2
linter-jade, v0.3.2
linter-jshint, v2.1.0
linter-php, v1.2.0
minimap, v4.24.6
minimap-highlight-selected, v4.4.0
php-debug, v0.2.3
pigments, v0.29.3
symbols-tree-view, v0.13.2
sync-settings, v0.7.2
visual-studio-dark-syntax, v0.1.0

# Dev
No dev packages
```

**Comment by Peekmo** [comment]
Hi,

Don't know why the error comes in that plugin, it seems to be an error with symbols-tree-view.
We both interact with the editor view, and symbols-tree-view seems to expect a "tags" everywhere, but I don't have "tags".

I think that this error has to be fixed by the other plugin.
