### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by poci-hu** [Peekmo/atom-autocomplete-php#284]
Tried to save a jsx file

**Atom Version**: 1.9.8
**System**: Microsoft Windows 10 Pro
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.18.9

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At C:\Users\poci\AppData\Local\atom\app-1.9.8\resources\app.asar\src\decoration-manager.js:192

Error: Cannot decorate a destroyed marker
    at DecorationManager.module.exports.DecorationManager.decorateMarker (C:\Users\poci\AppData\Local\atom\app-1.9.8\resources\app.asar\src\decoration-manager.js:192:15)
    at TextEditor.module.exports.TextEditor.decorateMarker (C:\Users\poci\AppData\Local\atom\app-1.9.8\resources\app.asar\src\text-editor.js:1528:37)
    at ClassProvider.module.exports.ClassProvider.addMarkerToCommentLine (file:///C:/Users/poci/.atom/packages/atom-autocomplete-php/lib/goto/class-provider.coffee:117:28)
    at ClassProvider.module.exports.ClassProvider.registerMarkers (file:///C:/Users/poci/.atom/packages/atom-autocomplete-php/lib/goto/class-provider.coffee:71:18)
    at ClassProvider.module.exports.AbstractProvider.rescanMarkers (file:///C:/Users/poci/.atom/packages/atom-autocomplete-php/lib/goto/abstract-provider.coffee:172:10)
    at file:///C:/Users/poci/.atom/packages/atom-autocomplete-php/lib/goto/abstract-provider.coffee:31:18
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\poci\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\text-buffer\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\poci\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\text-buffer\node_modules\event-kit\lib\emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\poci\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1156:27)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\poci\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1126:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\poci\AppData\Local\atom\app-1.9.8\resources\app.asar\src\text-editor.js:743:26)
    at Object.module.exports.AtomSaveAll.saveAll (file:///C:/Users/poci/.atom/packages/atom-save-all/lib/atom-save-all.coffee:18:18)
    at atom-text-editor.<anonymous> (file:///C:/Users/poci/.atom/packages/atom-save-all/lib/atom-save-all.coffee:6:72)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\poci\AppData\Local\atom\app-1.9.8\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\poci\AppData\Local\atom\app-1.9.8\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\poci\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\poci\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\poci\AppData\Local\atom\app-1.9.8\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\poci\AppData\Local\atom\app-1.9.8\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -0:16.2.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:16.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:13.1.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:13 core:move-right (atom-text-editor.editor.is-focused)
     -0:12.6.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:12.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:12.4.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:12.4.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:10.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:08.9.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:08.9.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:07.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:05.7.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:05.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:04.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:03.8.0 atom-save-all:saveAll (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "atom-autocomplete-php": {
    "binComposer": "C:/ProgramData/ComposerSetup/bin/composer.bat"
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.9 (active)
atom-bootstrap3, v1.2.12 (inactive)
atom-save-all, v0.4.1 (active)
auto-detect-indentation, v1.1.0 (active)
auto-indent, v0.5.0 (active)
autoclose-html, v0.23.0 (active)
docblockr, v0.8.2 (active)
highlight-selected, v0.11.2 (active)
language-blade, v0.25.3 (active)
linter, v1.11.16 (active)
linter-php, v1.2.0 (active)
merge-conflicts, v1.4.4 (active)
minimap, v4.24.7 (active)
php-extract-method, v0.2.1 (active)
react, v0.16.0 (active)
Sublime-Style-Column-Selection, v1.7.2 (active)
todo-show, v1.7.0 (inactive)
atom-dark-syntax, v0.27.0 (active)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by derpoho** [comment]
On every save of specific PHP Files.

**Atom Version**: 1.9.8
**System**: Mac OS X 10.11.6
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.18.9


### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:1026

Error: Cannot decorate a destroyed marker
    at DecorationManager.module.exports.DecorationManager.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/decoration-manager.js:192:15)
    at TextEditor.module.exports.TextEditor.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1528:37)
    at ClassProvider.module.exports.ClassProvider.addMarkerToCommentLine (/Users/user/.atom/packages/atom-autocomplete-php/lib/goto/class-provider.coffee:117:28)
    at ClassProvider.module.exports.ClassProvider.registerMarkers (/Users/user/.atom/packages/atom-autocomplete-php/lib/goto/class-provider.coffee:71:18)
    at ClassProvider.module.exports.AbstractProvider.rescanMarkers (/Users/user/.atom/packages/atom-autocomplete-php/lib/goto/abstract-provider.coffee:172:10)
    at /Users/user/.atom/packages/atom-autocomplete-php/lib/goto/abstract-provider.coffee:31:18
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1156:27)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1126:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:743:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:734:18)
    at Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:3:61)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:717:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:699:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:220:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:35.6.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:35.6.0 editor:newline (atom-text-editor.editor.is-focused)
  9x -0:32.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:21.3.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:21.3.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:21.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:19.9.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:19.9.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:19.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:17.2.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:16.8.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -0:16 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:12.1.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:11.6.0 core:delete (atom-text-editor.editor.is-focused)
     -0:09.7.0 autoclose-html:close-and-complete (atom-text-editor.editor.is-focused)
     -0:00.1.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "language-objective-c",
      "language-less",
      "language-java",
      "language-go",
      "language-csharp",
      "language-coffee-script",
      "language-clojure",
      "language-c",
      "language-perl",
      "language-ruby-on-rails",
      "language-toml",
      "open-on-github",
      "welcome",
      "activate-power-mode",
      "language-ocaml",
      "nuclide",
      "tool-bar",
      "minimap",
      "vim-mode",
      "atom-tag-wrapper",
      "SFTP-deployment",
      "standard-formatter",
      "linter-sass-lint"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      ".vagrant",
      "node_modules"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.3 (inactive)
atom-alignment, v0.12.1 (active)
atom-autocomplete-php, v0.18.9 (active)
atom-wrap-in-tag, v0.6.0 (inactive)
auto-update-packages, v1.0.1 (active)
autoclose-html, v0.23.0 (active)
autocomplete-modules, v1.6.1 (active)
docblockr, v0.8.2 (active)
duplicate-line-or-selection, v0.5.0 (inactive)
editorconfig, v1.4.1 (active)
emmet, v2.4.3 (active)
file-icons, v1.7.18 (active)
highlight-line, v0.11.1 (active)
highlight-selected, v0.11.2 (active)
language-babel, v2.32.2 (active)
language-docker, v1.1.7 (active)
language-docker-erb, v0.1.0 (active)
language-javascript-jsx, v0.3.7 (active)
language-terraform, v0.7.4 (active)
linter, v1.11.16 (active)
linter-eslint, v7.2.4 (active)
linter-js-standard, v3.4.1 (active)
linter-php, v1.2.0 (active)
linter-sass-lint, v1.7.0 (inactive)
monokai, v0.18.0 (active)
monokai-seti, v0.7.0 (inactive)
pigments, v0.31.2 (active)
predawn-syntax, v1.0.2 (inactive)
predawn-ui, v1.0.2 (inactive)
project-plus, v0.9.0 (active)
project-quick-open, v0.5.0 (inactive)
react-snippets, v0.4.2 (active)
seti-ui, v1.3.2 (inactive)
standard-formatter, v2.0.1 (inactive)
terminal-plus, v0.14.5 (active)
toggle-quotes, v1.0.0 (active)
vim-mode, v0.65.1 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (active)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (active)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (inactive)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.0 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (inactive)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (inactive)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (inactive)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by Rulsky** [comment]
sometimes happens to me when working with spec(test cases) for PHPunit.

stack Trace:
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.1
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.20.2


### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:1030

Error: Cannot decorate a destroyed marker
    at DecorationManager.module.exports.DecorationManager.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/decoration-manager.js:192:15)
    at TextEditor.module.exports.TextEditor.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1662:37)
    at FunctionProvider.module.exports.AbstractProvider.placeAnnotation (/Users/rulsky/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:127:29)
    at FunctionProvider.<anonymous> (/Users/rulsky/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:92:18)
    at FunctionProvider.module.exports.AbstractProvider.registerAnnotations (/Users/rulsky/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:91:13)
    at FunctionProvider.module.exports.AbstractProvider.rescan (/Users/rulsky/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:236:10)
    at /Users/rulsky/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:24:18
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1154:27)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1124:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:871:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:738:18)
    at Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:721:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:693:35)
    at atom-workspace.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:222:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:37.7.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:37.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:31.2.0 core:copy (atom-text-editor.editor.is-focused)
     -0:24.4.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:23.9.0 core:copy (atom-text-editor.editor.is-focused)
     -0:20.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:20.2.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:20.2.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:20.2.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:19.9.0 core:paste (atom-text-editor.editor.is-focused)
     -0:19 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:19 editor:newline (atom-text-editor.editor.is-focused)
     -0:18.8.0 core:paste (atom-text-editor.editor.is-focused)
     -0:17.2.0 core:select-up (atom-text-editor.editor.is-focused)
     -0:16.3.0 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
     -0:00.1.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "php-debug"
    ],
    "projectHome": "/Users/rulsky/dev",
    "telemetryConsent": "limited",
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "useCustomTitleBar": true
  },
  "atom-autocomplete-php": {
    "autoloadPaths": [
      "vendor/autoload.php",
      "autoload.php",
      "src/autoload.php"
    ],
    "insertNewlinesForUseStatements": true
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.22.3 (active)
aligner-css, v1.2.0 (active)
aligner-javascript, v1.0.0 (active)
aligner-php, v1.0.0 (active)
aligner-scss, v1.1.0 (active)
atom-autocomplete-php, v0.20.2 (active)
atom-material-syntax, v0.4.6 (active)
atom-material-syntax-dark, v0.2.5 (inactive)
atom-material-syntax-light, v0.4.5 (inactive)
atom-material-ui, v1.3.8 (active)
atom-ternjs, v0.16.1 (inactive)
autocomplete-json, v5.2.0 (active)
autocomplete-modules, v1.6.7 (active)
color-picker, v2.2.3 (active)
dash, v1.7.0 (inactive)
duotone-snow, v2.0.2 (inactive)
emmet, v2.4.3 (active)
es6-javascript, v1.0.0 (inactive)
highlight-selected, v0.11.2 (active)
hyperclick, v0.0.39 (active)
hyperclick-markdown, v0.2.2 (active)
hyperclick-php, v0.2.1 (active)
js-hyperclick, v1.9.0 (active)
language-pug, v0.0.19 (active)
linter, v1.11.18 (active)
linter-eslint, v8.0.0 (active)
linter-php, v1.3.1 (active)
markdown-preview-plus, v2.4.0 (active)
path-hyperclick, v0.3.0 (active)
php-debug, v0.2.4 (inactive)
php-getters-setters, v0.5.5 (active)
pigments, v0.37.0 (active)
Quick-JavaScript, v2.2.0 (active)
script, v3.12.2 (active)
seti-icons, v1.3.4 (active)
source-preview, v0.5.0 (inactive)
source-preview-pug, v0.2.0 (active)
spacegray-light-neue-ui, v0.1.5 (inactive)
white-ui, v2.4.1 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```
