### ISSUE TITLE
Error：Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by gychg** [Peekmo/atom-autocomplete-php#290]
/******/.atom/packages/atom-autocomplete-php/lib/tooltip/function-provider.coffee:51
Hide Stack Trace
TypeError: Cannot read property 'length' of undefined
    at FunctionProvider.module.exports.FunctionProvider.getTooltipForWord (file:///******/.atom/packages/atom-autocomplete-php/lib/tooltip/function-provider.coffee:44:33)
    at FunctionProvider.module.exports.AbstractProvider.showPopoverFor (file:///******/.atom/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:109:24)
    at HTMLSpanElement.<anonymous> (file:///******/.atom/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:78:22)
    at HTMLDivElement.jQuery.event.dispatch (******\.atom\packages\atom-autocomplete-php\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (******\.atom\packages\atom-autocomplete-php\node_modules\jquery\dist\jquery.js:4121:28)

**Comment by uonick** [comment]
[Enter steps to reproduce:]
1. Remove line from php file


**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.10
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package 0.22.2


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /home/developer/.atom/packages/atom-autocomplete-php/lib/tooltip/function-provider.coffee:48

TypeError: Cannot read property 'length' of undefined
    at FunctionProvider.module.exports.FunctionProvider.getTooltipForWord (/packages/atom-autocomplete-php/lib/tooltip/function-provider.coffee:48:33)
    at FunctionProvider.module.exports.AbstractProvider.showPopoverFor (/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:109:24)
    at /packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:78:22)
    at HTMLDivElement.dispatch (/packages/atom-autocomplete-php/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/atom-autocomplete-php/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  2x -7:57.1.0 emmet:expand-abbreviation-with-tab (input.hidden-input)
     -6:29.2.0 core:delete (input.hidden-input)
  3x -6:22.6.0 core:backspace (input.hidden-input)
  2x -4:48.9.0 core:delete (input.hidden-input)
  5x -4:41.9.0 core:backspace (input.hidden-input)
     -0:50.7.0 tree-view:duplicate (span.name.icon.php-icon)
  4x -0:47.8.0 core:select-left (input.hidden-input)
     -0:42.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
aligner 0.22.3 
aligner-php 1.0.0 
aligner-scss 1.1.0 
angular-2-typeScript-snippets 0.6.3 
angular2-snippets 0.3.0 
angular2-snippets-atom 0.7.0 
atom-autocomplete-php 0.22.2 
atom-beautify 0.29.17 
atom-typescript 10.1.15 
autocomplete-php 0.3.7 
blade-snippets 0.2.0 
cake-syntax 1.0.2 
dimmed-dark-ocean-syntax 1.0.1 
docblockr 0.9.1 
emmet 2.4.3 
es6-javascript 1.0.0 
file-icons 2.0.17 
git-plus 7.3.3 
highlight-selected 0.12.0 
language-blade 0.28.1 
language-gitignore 0.3.0 
language-ignore 1.5.2 
language-pug 0.0.21 
language-SCSS 0.4.0 
language-typescript-grammars-only 1.6.0 
language-volt 0.2.2 
language-vue 0.21.2 
language-vue-component 0.5.0 
laravel 0.7.1 
laravel-eloquent-snippets 2.0.0 
linter 2.1.0 
linter-php 1.3.1 
linter-phpcs 1.5.10 
linter-scss-lint 3.1.0 
linter-tslint 0.14.0 
linter-ui-default 1.1.0 
minimap 4.26.8 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.5.0 
minimap-selection 4.4.0 
new-tab 0.5.3 
php-analyser 0.2.0 
php-cs-fixer 4.1.0 
php-twig 4.0.0 
project-manager 3.3.3 
Quick-JavaScript 2.2.0 
Sublime-Style-Column-Selection 1.7.4 
symbol-gen 1.3.1 
tabs-to-spaces 1.0.3 
tree-view-git-status 1.3.1 
vue-autocomplete 0.1.1 
vue-snippets 0.6.0 
```
