### ISSUE TITLE
Cannot decorate a destroyed Marker error

### ISSUE THREAD

**Issue by philltrue** [Peekmo/atom-autocomplete-php#297]
Tried to Save a PHP file

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Microsoft Windows 10 Home
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.19.4

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /C:/projects/atom/out/app/src/pane.coffee:1030

Error: Cannot decorate a destroyed marker
    at DecorationManager.module.exports.DecorationManager.decorateMarker (C:\Users\True\AppData\Local\atom\app-1.11.2\resources\app.asar\src\decoration-manager.js:192:15)
    at TextEditor.module.exports.TextEditor.decorateMarker (C:\Users\True\AppData\Local\atom\app-1.11.2\resources\app.asar\src\text-editor.js:1657:37)
    at FunctionProvider.module.exports.AbstractProvider.placeAnnotation (file:///C:/Users/True/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:127:29)
    at FunctionProvider.<anonymous> (file:///C:/Users/True/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:92:18)
    at FunctionProvider.module.exports.AbstractProvider.registerAnnotations (file:///C:/Users/True/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:91:13)
    at FunctionProvider.module.exports.AbstractProvider.rescan (file:///C:/Users/True/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:236:10)
    at file:///C:/Users/True/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:24:18
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\True\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\True\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\True\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1154:27)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\True\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1124:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\True\AppData\Local\atom\app-1.11.2\resources\app.asar\src\text-editor.js:866:26)
    at Pane.module.exports.Pane.saveItem (C:\Users\True\AppData\Local\atom\app-1.11.2\resources\app.asar\src\pane.js:738:18)
    at Pane.saveItem (C:\Users\True\AppData\Local\atom\app-1.11.2\resources\app.asar\src\pane.js:3:61)
    at Pane.module.exports.Pane.saveActiveItem (C:\Users\True\AppData\Local\atom\app-1.11.2\resources\app.asar\src\pane.js:721:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\True\AppData\Local\atom\app-1.11.2\resources\app.asar\src\workspace.js:694:35)
    at atom-workspace.commandRegistry.add.core:save (C:\Users\True\AppData\Local\atom\app-1.11.2\resources\app.asar\src\register-default-commands.js:220:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\True\AppData\Local\atom\app-1.11.2\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\True\AppData\Local\atom\app-1.11.2\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\True\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\True\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\True\AppData\Local\atom\app-1.11.2\resources\app.asar\src\window-event-handler.js:114:36)
    at HTMLDocument.<anonymous> (C:\Users\True\AppData\Local\atom\app-1.11.2\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -3:03.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:02.6.0 core:save (atom-text-editor.editor.is-focused)
     -2:58.2.0 core:copy (atom-text-editor.editor.is-focused)
     -2:57.5.0 core:paste (atom-text-editor.editor.is-focused)
     -2:56.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:52.9.0 core:copy (atom-text-editor.editor.is-focused)
  3x -2:52.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:51.5.0 core:paste (atom-text-editor.editor.is-focused)
     -2:51 core:backspace (atom-text-editor.editor.is-focused)
     -2:50.4.0 core:save (atom-text-editor.editor.is-focused)
     -2:10.8.0 core:delete (atom-text-editor.editor.is-focused)
     -2:09.9.0 core:save (atom-text-editor.editor.is-focused)
     -2:02.3.0 atom-alignment:alignMultiple (atom-text-editor.editor.is-focused)
     -2:01.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:45.9.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -0:42.7.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "closeEmptyWindows": false,
    "destroyEmptyPanes": false,
    "telemetryConsent": "no"
  },
  "atom-autocomplete-php": {
    "binComposer": "C:\\ProgramData\\ComposerSetup\\bin\\composer.phar",
    "insertNewlinesForUseStatements": true
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1 (active)
atom-autocomplete-php, v0.19.4 (active)
docblockr, v0.8.7 (active)
emmet, v2.4.3 (active)
highlight-selected, v0.11.2 (active)
linter, v1.11.18 (active)
linter-php, v1.3.1 (active)
pigments, v0.37.0 (active)
project-manager, v3.2.5 (active)
simple-drag-drop-text, v0.3.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by tbillington** [comment]
Also getting this when saving a file

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Mac OS X 10.11.4
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.20.2


### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:1030

Error: Cannot decorate a destroyed marker
    at DecorationManager.module.exports.DecorationManager.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/decoration-manager.js:192:15)
    at TextEditor.module.exports.TextEditor.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1662:37)
    at FunctionProvider.module.exports.AbstractProvider.placeAnnotation (/Users/trent/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:127:29)
    at FunctionProvider.<anonymous> (/Users/trent/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:92:18)
    at FunctionProvider.module.exports.AbstractProvider.registerAnnotations (/Users/trent/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:91:13)
    at FunctionProvider.module.exports.AbstractProvider.rescan (/Users/trent/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:236:10)
    at /Users/trent/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:24:18
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1154:27)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1124:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:871:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:738:18)
    at Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:721:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:693:35)
    at atom-workspace.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:222:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:25.1.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
  4x -0:24.6.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:20.3.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
  5x -0:19.8.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:18.9.0 core:move-up (atom-text-editor.editor.is-focused)
  3x -0:18.6.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:18.1.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:16.5.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:16.1.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
  5x -0:16.1.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:15.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:15.1.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:14.9.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:14.6.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:13.6.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -0:12.9.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".hgrc",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "atom-typescript",
      "activate-power-mode",
      "vim-mode-plus",
      "gometalinter-linter",
      "language-javascript-jsx",
      "nuclide"
    ],
    "excludeVcsIgnoredPaths": false,
    "telemetryConsent": "no",
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v1.1.0 (inactive)
atom-autocomplete-php, v0.20.2 (active)
atom-beautify, v0.29.13 (active)
autocomplete-go, v1.3.0 (active)
builder-go, v1.0.1 (active)
color-picker, v2.2.3 (active)
file-icons, v1.7.25 (active)
go-config, v1.2.4 (active)
go-debug, v0.1.22 (active)
go-get, v2.1.1 (active)
go-plus, v4.3.2 (active)
go-signature-statusbar, v1.1.0 (active)
godoc, v1.1.1 (active)
gofmt, v1.2.0 (active)
gometalinter-linter, v1.2.2 (inactive)
gorename, v1.1.0 (active)
ide-purescript, v0.14.10 (inactive)
language-docker, v1.1.7 (active)
language-elm, v1.5.0 (active)
language-javascript-jsx, v0.3.7 (inactive)
language-protobuf, v0.7.0 (active)
language-purescript, v0.8.2 (active)
language-rust, v0.4.8 (active)
linter, v1.11.18 (active)
linter-eslint, v8.0.0 (active)
linter-flow, v5.5.0 (active)
linter-php, v1.3.1 (active)
navigator-go, v1.1.3 (active)
nuclide, v0.188.0 (inactive)
pigments, v0.37.0 (active)
racer, v0.20.0 (active)
react, v0.16.1 (active)
tester-go, v2.0.2 (active)
vim-mode-plus, v0.66.1 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (active)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```
