### ISSUE TITLE
Unexpected JSON end 

### ISSUE THREAD

**Issue by jonathan-dejong** [Peekmo/atom-autocomplete-php#302]
Just updated to latest version and now I get this error:
```
SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at ChildProcess.<anonymous> (/Users/jontedejong/.atom/packages/atom-autocomplete-php/lib/services/php-proxy.coffee:83:52)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
```

I tried updating Atom too to 1.12.3 but no dice.

**Comment by sharifzadesina** [comment]
Same problem...

**Comment by tomoat** [comment]
#303 Same problem...

**Comment by Peekmo** [comment]
Hello,

Should be fixed.
