### ISSUE TITLE
Uncaught Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by jeedem** [Peekmo/atom-autocomplete-php#324]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package 0.22.0

### Stack Trace

Uncaught Error: spawn UNKNOWN

```
At internal/child_process.js:313

Error: spawn UNKNOWN
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:392:9)
    at Object.execute (/packages/atom-autocomplete-php/lib/services/php-proxy.coffee:72:58)
    at Object.functions (/packages/atom-autocomplete-php/lib/services/php-proxy.coffee:190:14)
    at Object.getMemberContext (/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:678:27)
    at FunctionProvider.module.exports.FunctionProvider.getTooltipForWord (/packages/atom-autocomplete-php/lib/tooltip/function-provider.coffee:18:25)
    at FunctionProvider.module.exports.AbstractProvider.showPopoverFor (/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:109:24)
    at /packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:78:22)
    at HTMLDivElement.dispatch (/packages/atom-autocomplete-php/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/atom-autocomplete-php/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -2:02.7.0 core:move-up (input.hidden-input)
     -2:02.7.0 docblockr:parse-tab (input.hidden-input)
     -2:02.7.0 snippets:next-tab-stop (input.hidden-input)
     -2:02.7.0 snippets:expand (input.hidden-input)
     -2:02.7.0 editor:indent (input.hidden-input)
 13x -1:59.1.0 core:backspace (input.hidden-input)
     -1:38.3.0 core:copy (input.hidden-input)
     -1:36.8.0 core:paste (input.hidden-input)
  2x -1:36.6.0 core:save (input.hidden-input)
     -0:39.2.0 find-and-replace:show (input.hidden-input)
     -0:38.1.0 core:confirm (input.hidden-input)
  3x -0:37.5.0 core:backspace (input.hidden-input)
  3x -0:36.2.0 core:confirm (input.hidden-input)
  4x -0:35.6.0 core:backspace (input.hidden-input)
     -0:34.4.0 core:save (input.hidden-input)
  3x -0:32.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.22.0 
atom-beautify 0.29.17 
atom-symfony2 0.2.1 
docblockr 0.9.1 
docs-snippets 0.8.0 
file-icons 2.0.17 
linter 1.11.23 
linter-php 1.3.1 
php-getters-setters 0.5.5 
php-twig 4.0.0 
remote-edit 1.9.0 
remote-sync 4.1.5 
```

**Comment by Akumetsu-Dev** [comment]
same error.

Atom Version:
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git

**Comment by Dayjo** [comment]
I am receiving this error when I run the Namespace command. 

```
Uncaught Error
~/.atom/packages/atom-autocomplete-php/lib/services/php-proxy.coffee:130
```

Unfortunately the 'copy error report to clipboard' didn't work. 

Atom 1.18.0
OS X El Capitan 10.11.6 (15G1217)
