### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by myleshyson** [Peekmo/atom-autocomplete-php#329]
Getting this whenever I go to the ModelFactory.php file in Laravel. 

TypeError: Cannot read property 'length' of undefined
    at FunctionProvider.module.exports.FunctionProvider.getTooltipForWord (/Users/myleshyson/.atom/packages/atom-autocomplete-php/lib/tooltip/function-provider.coffee:48:33)
    at FunctionProvider.module.exports.AbstractProvider.showPopoverFor (/Users/myleshyson/.atom/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:109:24)
    at HTMLSpanElement.<anonymous> (/Users/myleshyson/.atom/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:78:22)
    at HTMLDivElement.dispatch (/Users/myleshyson/.atom/packages/atom-autocomplete-php/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/Users/myleshyson/.atom/packages/atom-autocomplete-php/node_modules/jquery/dist/jquery.js:4121:28)

**Comment by myleshyson** [comment]
Nevermind, it fixed whenever I unchecked the "Exclude VCS Ignored Paths" option under the Core Settings.

**Comment by Maurifc** [comment]
It's happening here too.

**Comment by GaspariLab** [comment]
Confirmed, happening here too on Atom 1.17.2 and package version 0.22.2.

**Comment by eddyb2017** [comment]
Confirmed! Happened to me too, Atom 1.15.0 on Linux, package version 0.23.1

**Comment by jeffersonPinoDeveloper** [comment]
confirmed! Also happen on Atom 1.17.2 on Mac.

**Comment by jeffersonPinoDeveloper** [comment]
confirmed! Also happen on Atom 1.17.2 on Mac.

**Comment by Peekmo** [comment]
Hello,

I tried on a new laravel project, didn't get your error. I pushed something, could you please test ?
