### ISSUE TITLE
Failed to activate the atom-autocomplete-php package

### ISSUE THREAD

**Issue by dsambugaro** [Peekmo/atom-autocomplete-php#351]
When I active the atom-autocomplete-php package, that happens:

```
Arguments to CompositeDisposable.add must have a .dispose() method
Hide Stack Trace
TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/usr/lib/atom/node_modules/event-kit/lib/composite-disposable.js:74:13)
    at CompositeDisposable.module.exports.CompositeDisposable.add (/usr/lib/atom/node_modules/event-kit/lib/composite-disposable.js:43:11)
    at requireAutocompleteManagerAsync (/usr/lib/atom/node_modules/autocomplete-plus/lib/main.js:105:23)
    at Object.requireAutocompleteManagerAsync (/usr/lib/atom/node_modules/autocomplete-plus/lib/main.js:26:9)
    at Object.consumeProvider (/usr/lib/atom/node_modules/autocomplete-plus/lib/main.js:102:10)
    at Object.consumeProvider_2_0 (/usr/lib/atom/node_modules/autocomplete-plus/lib/main.js:81:17)
    at Provider.module.exports.Provider.provide (/usr/lib/atom/node_modules/service-hub/lib/provider.js:34:52)
    at ServiceHub.module.exports.ServiceHub.provide (/usr/lib/atom/node_modules/service-hub/lib/service-hub.js:30:20)
    at Package.module.exports.Package.activateServices (/usr/lib/atom/src/package.js:444:71)
    at Package.module.exports.Package.activateNow (/usr/lib/atom/src/package.js:254:16)
    at /usr/lib/atom/src/package.js:223:32
    at Package.module.exports.Package.measure (/usr/lib/atom/src/package.js:97:15)
    at /usr/lib/atom/src/package.js:216:26
    at Package.module.exports.Package.activate (/usr/lib/atom/src/package.js:213:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/lib/atom/src/package-manager.js:635:34)
    at /usr/lib/atom/src/package-manager.js:367:19
    at /usr/lib/atom/src/config.js:642:20
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:141:28)
    at Config.module.exports.Config.emitChangeEvent (/usr/lib/atom/src/config.js:833:29)
    at Config.module.exports.Config.setRawValue (/usr/lib/atom/src/config.js:619:19)
    at Config.module.exports.Config.set (/usr/lib/atom/src/config.js:234:14)
    at Config.module.exports.Config.removeAtKeyPath (/usr/lib/atom/src/config.js:384:12)
    at Package.module.exports.Package.enable (/usr/lib/atom/src/package.js:82:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/usr/lib/atom/src/package-manager.js:178:14)
    at HTMLButtonElement.enablementButtonClickHandler (/usr/lib/atom/node_modules/settings-view/lib/package-card.js:353:25)
```

**Comment by Tejbahadur** [comment]
I am also getting this same type of issue.

`Arguments to CompositeDisposable.add must have a .dispose() method
Hide Stack Trace
TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/private/var/folders/jq/0c0f52691d142jkqtldnmdhw0000gp/T/AppTranslocation/3A791478-80E6-47B5-923C-9EAABD6373F6/d/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/composite-disposable.js:74:19)
    at CompositeDisposable.module.exports.CompositeDisposable.add (/private/var/folders/jq/0c0f52691d142jkqtldnmdhw0000gp/T/AppTranslocation/3A791478-80E6-47B5-923C-9EAABD6373F6/d/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/composite-disposable.js:43:17)
    at requireAutocompleteManagerAsync (/private/var/folders/jq/0c0f52691d142jkqtldnmdhw0000gp/T/AppTranslocation/3A791478-80E6-47B5-923C-9EAABD6373F6/d/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/main.js:110:29)
    at Object.requireAutocompleteManagerAsync (/private/var/folders/jq/0c0f52691d142jkqtldnmdhw0000gp/T/AppTranslocation/3A791478-80E6-47B5-923C-9EAABD6373F6/d/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/main.js:31:15)
    at Object.consumeProvider (/private/var/folders/jq/0c0f52691d142jkqtldnmdhw0000gp/T/AppTranslocation/3A791478-80E6-47B5-923C-9EAABD6373F6/d/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/main.js:107:16)
    at Object.consumeProvider_2_0 (/private/var/folders/jq/0c0f52691d142jkqtldnmdhw0000gp/T/AppTranslocation/3A791478-80E6-47B5-923C-9EAABD6373F6/d/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/main.js:86:23)
    at Provider.module.exports.Provider.provide (/private/var/folders/jq/0c0f52691d142jkqtldnmdhw0000gp/T/AppTranslocation/3A791478-80E6-47B5-923C-9EAABD6373F6/d/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (/private/var/folders/jq/0c0f52691d142jkqtldnmdhw0000gp/T/AppTranslocation/3A791478-80E6-47B5-923C-9EAABD6373F6/d/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.module.exports.Package.activateServices (/private/var/folders/jq/0c0f52691d142jkqtldnmdhw0000gp/T/AppTranslocation/3A791478-80E6-47B5-923C-9EAABD6373F6/d/Atom.app/Contents/Resources/app/src/package.js:446:77)
    at Package.module.exports.Package.activateNow (/private/var/folders/jq/0c0f52691d142jkqtldnmdhw0000gp/T/AppTranslocation/3A791478-80E6-47B5-923C-9EAABD6373F6/d/Atom.app/Contents/Resources/app/src/package.js:256:22)
    at /private/var/folders/jq/0c0f52691d142jkqtldnmdhw0000gp/T/AppTranslocation/3A791478-80E6-47B5-923C-9EAABD6373F6/d/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/private/var/folders/jq/0c0f52691d142jkqtldnmdhw0000gp/T/AppTranslocation/3A791478-80E6-47B5-923C-9EAABD6373F6/d/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /private/var/folders/jq/0c0f52691d142jkqtldnmdhw0000gp/T/AppTranslocation/3A791478-80E6-47B5-923C-9EAABD6373F6/d/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/private/var/folders/jq/0c0f52691d142jkqtldnmdhw0000gp/T/AppTranslocation/3A791478-80E6-47B5-923C-9EAABD6373F6/d/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/private/var/folders/jq/0c0f52691d142jkqtldnmdhw0000gp/T/AppTranslocation/3A791478-80E6-47B5-923C-9EAABD6373F6/d/Atom.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /private/var/folders/jq/0c0f52691d142jkqtldnmdhw0000gp/T/AppTranslocation/3A791478-80E6-47B5-923C-9EAABD6373F6/d/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:519:35
    at exit (/private/var/folders/jq/0c0f52691d142jkqtldnmdhw0000gp/T/AppTranslocation/3A791478-80E6-47B5-923C-9EAABD6373F6/d/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/private/var/folders/jq/0c0f52691d142jkqtldnmdhw0000gp/T/AppTranslocation/3A791478-80E6-47B5-923C-9EAABD6373F6/d/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at /private/var/folders/jq/0c0f52691d142jkqtldnmdhw0000gp/T/AppTranslocation/3A791478-80E6-47B5-923C-9EAABD6373F6/d/Atom.app/Contents/Resources/app/src/buffered-process.js:359:17
    at Socket.<anonymous> (/private/var/folders/jq/0c0f52691d142jkqtldnmdhw0000gp/T/AppTranslocation/3A791478-80E6-47B5-923C-9EAABD6373F6/d/Atom.app/Contents/Resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)`

**Comment by Kravinskiy** [comment]
Any solutions yet? +1

**Comment by amigabits** [comment]
Same issue here since disabling the atom-autocomplete-php package.

The reason I disabled in the first instance is because indexing wasn't completing (which has also been reported here). For me this started around atom 1.19.x, and the macos console was logging a stream of taskgated errors,

default	14:49:20.769914 +0100	taskgated	MacOS error: -67062

**Comment by mattschinkel** [comment]
Same issue here when I add atom-autocomplete php. I am on windows 10.

**Comment by andreiciceu** [comment]
Same issue on MacOS. Any solutions?

**Comment by thexeos** [comment]
Still an issue with latest everything. Anybody managed to get it to work?

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Home
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package 0.25.6

**Comment by rubo77** [comment]
upgrade all packages and this fixed the issue. type this in your terminal console:

    apm update
