### ISSUE TITLE
Uncaught TypeError: element.indexOf is not a function

### ISSUE THREAD

**Issue by kusmierczykw** [Peekmo/atom-autocomplete-php#352]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package 0.25.6

### Stack Trace

Uncaught TypeError: element.indexOf is not a function

```
At C:\Users\wojci\.atom\packages\atom-autocomplete-php\lib\services\php-file-parser.coffee:479

TypeError: element.indexOf is not a function
    at Object.parseStackClass (/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:479:21)
    at Object.getStackClasses (/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:410:19)
    at Object.getCalledClass (/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:30:23)
    at Object.getMemberContext (/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:609:28)
    at FunctionProvider.module.exports.FunctionProvider.getTooltipForWord (/packages/atom-autocomplete-php/lib/tooltip/function-provider.coffee:32:27)
    at FunctionProvider.module.exports.AbstractProvider.showPopoverFor (/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:166:26)
    at /packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:114:28)
    at HTMLDivElement.dispatch (/packages/todo-show/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/todo-show/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  3x -7:20.7.0 core:backspace (input.hidden-input)
     -7:17.5.0 core:confirm (input.hidden-input)
     -6:58.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
 30x -6:47.8.0 core:backspace (input.hidden-input)
     -6:36.6.0 editor:consolidate-selections (input.hidden-input)
     -6:36.6.0 core:cancel (input.hidden-input)
     -6:36.2.0 editor:consolidate-selections (input.hidden-input)
     -6:36.2.0 core:cancel (input.hidden-input)
     -6:05.0 core:paste (input.hidden-input)
     -6:04.6.0 core:confirm (input.hidden-input)
  2x -5:42.6.0 core:backspace (input.hidden-input)
     -5:42.1.0 snippets:next-tab-stop (input.hidden-input)
     -5:42.1.0 snippets:expand (input.hidden-input)
     -5:42.1.0 editor:indent (input.hidden-input)
     -1:31.6.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
aligner-php 1.1.1 
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.4 
atom-live-server 2.1.2 
atom-ternjs 0.18.3 
atom-wordpress 0.3.0 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autocomplete 0.47.0 
autocomplete-php 0.3.7 
autocomplete-wordpress-hooks 0.2.2 
busy-signal 1.4.3 
emmet 2.4.3 
file-icons 2.1.8 
highlight-selected 0.13.1 
intentions 1.1.2 
linter 2.2.0 
linter-ui-default 1.6.2 
livereload 0.4.4 
minimap 4.28.3 
minimap-highlight-selected 4.6.1 
pigments 0.39.1 
project-manager 3.3.5 
todo-show 1.11.0 
wordpress 0.2.0 
wordpress-api 1.2.2 
wordpress-dictionary 4.4.0 
wordpress-suite 1.1.1 
wp-dev 0.3.5 
```

**Comment by armincpath** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.5 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package 0.25.6


### Stack Trace

Uncaught TypeError: element.indexOf is not a function

```
At C:\Users\aanton\.atom\packages\atom-autocomplete-php\lib\services\php-file-parser.coffee:532

TypeError: element.indexOf is not a function
    at Object.parseStackClass (/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:532:24)
    at Object.getStackClasses (/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:459:17)
    at Object.getCalledClass (/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:28:21)
    at Object.getMemberContext (/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:679:28)
    at FunctionProvider.module.exports.FunctionProvider.getTooltipForWord (/packages/atom-autocomplete-php/lib/tooltip/function-provider.coffee:18:25)
    at FunctionProvider.module.exports.AbstractProvider.showPopoverFor (/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:108:24)
    at /packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:77:22)
    at HTMLDivElement.dispatch (/packages/atom-autocomplete-php/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/atom-autocomplete-php/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  2x -2:32.2.0 core:backspace (input.hidden-input)
     -2:31.4.0 core:confirm (input.hidden-input)
  2x -0:35.1.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
aligner 1.2.4 
aligner-javascript 1.3.0 
aligner-php 1.1.1 
api-docs 0.0.6 
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.5 
atom-minify 0.8.0 
atom-monokai-php 1.0.0 
atom-ternjs 0.18.3 
atom-wordpress 0.3.0 
autocomplete-modules 1.7.0 
autocomplete-php 0.3.7 
autocomplete-wordpress-hooks 0.2.3 
bootstrap3-snippets 0.1.2 
busy-signal 1.4.3 
color-picker 2.2.5 
composer 0.5.0 
docblockr 0.11.0 
editorconfig 2.2.2 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
git-plus 7.9.3 
highlight-selected 0.13.1 
hyperclick 0.1.3 
intentions 1.1.5 
language-htaccess 0.1.1 
language-markdown 0.25.1 
linter 2.2.0 
linter-csslint 2.0.0 
linter-htmlhint 1.3.3 
linter-js-yaml 1.2.7 
linter-jshint 3.1.5 
linter-json-lint 0.1.2 
linter-php 1.4.0 
linter-phpcs 1.6.7 
linter-phpmd 1.5.3 
linter-scss-lint 3.1.1 
linter-tidy 2.3.1 
linter-ui-default 1.6.8 
linter-write-good 0.9.0 
logo-file-icons 1.11.0 
minimap 4.29.6 
minimap-autohide 0.10.1 
minimap-linter 2.0.2 
minimap-selection 4.5.0 
php-cs-fixer 4.1.1 
php-debug 0.2.5 
php-integrator-annotations 1.2.0 
php-integrator-autocomplete-plus 1.6.0 
php-integrator-autocomplete-plus-legacy-php56 1.0.1 
php-integrator-base 3.0.1 
php-integrator-base-legacy-php56 1.0.1 
php-integrator-call-tips-legacy-php56 1.2.3 
php-integrator-linter-legacy-php56 1.3.1 
php-integrator-navigation 1.2.1 
php-integrator-navigation-legacy-php56 1.0.1 
php-integrator-refactoring 1.4.1 
php-integrator-refactoring-legacy-php56 1.0.1 
php-integrator-symbol-viewer 0.6.4 
php-integrator-tooltips-legacy-php56 1.1.6 
php-light-syntax 1.0.2 
pigments 0.40.2 
project-manager 3.3.5 
remote-sync 4.1.5 
sync-settings 0.8.3 
todo-show 2.0.0 
wordpress-api 1.2.2 
wordpress-autocomplete 1.2.0 
wordpress-dictionary 4.4.0 
wordpress-suite 1.1.1 
xeta-syntax 0.5.0 
```

**Comment by aurovrata** [comment]
I changed the line 532 in the file ~/.atom\packages\atom-autocomplete-php\lib\services\php-file-parser.coffee to,

`if typeof element == 'string' or element instanceof String and element.indexOf('()') != -1`

I am assuming that some of the php  picked up by the parser are not instances of strings and the therefore the string property indexOf throws an error.

**Comment by annalinneajohansson** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Ubuntu 17.04
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package 0.25.6


### Stack Trace

Uncaught TypeError: element.indexOf is not a function

```
At /home/anna/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:532

TypeError: element.indexOf is not a function
    at Object.parseStackClass (/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:532:24)
    at Object.getStackClasses (/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:459:17)
    at Object.getCalledClass (/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:28:21)
    at Object.getMemberContext (/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:679:28)
    at FunctionProvider.module.exports.FunctionProvider.getTooltipForWord (/packages/atom-autocomplete-php/lib/tooltip/function-provider.coffee:18:25)
    at FunctionProvider.module.exports.AbstractProvider.showPopoverFor (/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:108:24)
    at /packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:77:22)
    at HTMLDivElement.dispatch (/packages/atom-autocomplete-php/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/atom-autocomplete-php/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -1:15.1.0 snippets:next-tab-stop (input.hidden-input)
     -1:11.3.0 autocomplete-plus:confirm (input.hidden-input)
     -1:10.9.0 docblockr:parse-tab (input.hidden-input)
     -1:10.9.0 snippets:next-tab-stop (input.hidden-input)
     -1:06.7.0 docblockr:parse-tab (input.hidden-input)
     -1:06.7.0 snippets:next-tab-stop (input.hidden-input)
     -1:06.7.0 snippets:expand (input.hidden-input)
     -1:06.6.0 editor:indent (input.hidden-input)
     -1:05.9.0 core:backspace (input.hidden-input)
     -1:00.6.0 docblockr:parse-tab (input.hidden-input)
     -1:00.6.0 snippets:next-tab-stop (input.hidden-input)
     -1:00.6.0 snippets:expand (input.hidden-input)
     -1:00.6.0 editor:indent (input.hidden-input)
     -0:59.9.0 core:backspace (input.hidden-input)
     -0:58.2.0 docblockr:parse-enter (input.hidden-input)
     -0:58.2.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
aligner 1.2.4 
aligner-css 1.2.1 
aligner-javascript 1.3.0 
aligner-php 1.2.0 
aligner-scss 1.3.1 
atom-autocomplete-php 0.25.6 
atom-ide-ui 0.3.1 
atom-phpcs 1.7.3 
atom-ternjs 0.18.3 
atom-wordpress 0.3.0 
autoclose-html 0.23.0 
autocomplete-wordpress-hooks 0.2.3 
color-picker 2.2.5 
craft-twig 0.4.0 
dash-syntax 0.3.0 
docblockr 0.11.0 
file-icons 2.1.11 
git-plus 7.9.3 
ide-php 0.6.1 
jQuery 1.2.5 
jquery-snippets 11.0.0 
language-log 1.8.0 
project-manager 3.3.5 
todo-show 2.0.0 
wordpress 0.2.0 
wordpress-api 1.2.2 
wordpress-autocomplete 1.2.0 
wordpress-suite 1.1.1 
wp-dev 0.3.5 
```

**Comment by MrSiNiSt3R** [comment]
[Enter steps to reproduce:]

1. Firmly take a hold of your mouse
2. Wiggle it over the c0d3
3. Enjoy red boxes in ur scr33n!

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Kali GNU/Linux
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package 0.25.6
**User**: root

### Stack Trace

Uncaught TypeError: element.indexOf is not a function

```
At /root/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:532

TypeError: element.indexOf is not a function
    at Object.parseStackClass (/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:532:24)
    at Object.getStackClasses (/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:459:17)
    at Object.getCalledClass (/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:28:21)
    at Object.getMemberContext (/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:679:28)
    at FunctionProvider.module.exports.FunctionProvider.getTooltipForWord (/packages/atom-autocomplete-php/lib/tooltip/function-provider.coffee:18:25)
    at FunctionProvider.module.exports.AbstractProvider.showPopoverFor (/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:108:24)
    at /packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:77:22)
    at HTMLDivElement.dispatch (/packages/php-debug/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/php-debug/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  2x -6:49.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax-dark.theme-atom-dark-ui)
  2x -5:13.1.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -2:08.8.0 php-debug:toggleDebugging (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.9 
atom-browser 0.53.0 
atom-clock 0.1.15 
atom-live-server 2.2.0 
atom-material-numix-syntax 0.2.1 
atom-material-syntax 1.0.7 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.0.6 
atom-pair 2.0.13 
atom-wordpress 0.3.0 
autocomplete-wordpress-hooks 0.2.3 
busy-signal 1.4.3 
file-icons 2.1.14 
firewatch-syntax 1.1.1 
genesis-syntax 1.0.9 
genesis-ui 0.5.0 
geneus-ui 1.1.1 
go-debug 1.5.2 
hey-pane 1.1.0 
hydra-syntax-theme 4.0.1 
Hydrogen 2.1.1 
local-server-express 0.3.1 
material 2.2.0 
material-design-syntax 1.8.0 
material-monokai-syntax 1.0.1 
material-syntax 0.6.1 
material-ui 1.0.10 
minimap 4.29.7 
monokai 0.24.0 
monokai-seti 0.9.0 
node-debugger 1.10.1 
one-dark-shade-ui 0.1.0 
one-dark-vivid-syntax 1.8.0 
php-debug 0.2.5 
python-debugger 0.2.0 
rainbow-delimiters 2.1.2 
seti-syntax 1.1.3 
seti-ui 1.9.0 
seti-ui-beta 0.1.1 
seti-ui-red 0.13.0 
sourcemap 0.1.0 
teletype 0.2.3 
tomorrow-night-eighties-syntax 1.0.2 
woocommerce 1.0.0 
wordpress 0.2.0 
wordpress-api 1.2.2 
wordpress-dictionary 4.4.0 
wordpress-suite 1.2.0 
zentabs 0.8.9 
```

**Comment by shikkaba** [comment]
Any updates on this one? It's popping up constantly.

**Comment by MrSiNiSt3R** [comment]
disable it
