### ISSUE TITLE
could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.

### ISSUE THREAD

**Issue by edudix** [Peekmo/atom-autocomplete-php#360]
Hi, 
every time Im opening the Atom Im getting this error. Somtimes annoying.
I´ve been trying to find a solution without success. Im using Win10 and my php is installed on Xammp environment.
Best

**Comment by Fahmid-Shuvo** [comment]
Hello,
I am a beginner PHP learner. I have faced the same problem ..??
Help please...

Uncaught Error: spawn php ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by zhihuinvshen** [comment]
exactly same issue
https://github.com/Peekmo/atom-autocomplete-php/issues/388

**Comment by ParastooI** [comment]
same issue
