### ISSUE TITLE
Failed to activate the atom-autocomplete-php package v 0.25.6

### ISSUE THREAD

**Issue by tientranhpct** [Peekmo/atom-autocomplete-php#364]
TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (C:\Users\TienTran\AppData\Local\atom\app-1.18.0\resources\app\node_modules\event-kit\lib\composite-disposable.js:74:19)
    at CompositeDisposable.module.exports.CompositeDisposable.add (C:\Users\TienTran\AppData\Local\atom\app-1.18.0\resources\app\node_modules\event-kit\lib\composite-disposable.js:43:17)
    at requireAutocompleteManagerAsync (C:\Users\TienTran\AppData\Local\atom\app-1.18.0\resources\app\node_modules\autocomplete-plus\lib\main.js:110:29)
    at Object.requireAutocompleteManagerAsync (C:\Users\TienTran\AppData\Local\atom\app-1.18.0\resources\app\node_modules\autocomplete-plus\lib\main.js:31:15)
    at Object.consumeProvider (C:\Users\TienTran\AppData\Local\atom\app-1.18.0\resources\app\node_modules\autocomplete-plus\lib\main.js:107:16)
    at Object.consumeProvider_2_0 (C:\Users\TienTran\AppData\Local\atom\app-1.18.0\resources\app\node_modules\autocomplete-plus\lib\main.js:86:23)
    at Provider.module.exports.Provider.provide (C:\Users\TienTran\AppData\Local\atom\app-1.18.0\resources\app\node_modules\service-hub\lib\provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (C:\Users\TienTran\AppData\Local\atom\app-1.18.0\resources\app\node_modules\service-hub\lib\service-hub.js:30:26)
    at Package.module.exports.Package.activateServices (C:\Users\TienTran\AppData\Local\atom\app-1.18.0\resources\app\src\package.js:446:77)
    at Package.module.exports.Package.activateNow (C:\Users\TienTran\AppData\Local\atom\app-1.18.0\resources\app\src\package.js:256:22)
    at C:\Users\TienTran\AppData\Local\atom\app-1.18.0\resources\app\src\package.js:225:38
    at Package.module.exports.Package.measure (C:\Users\TienTran\AppData\Local\atom\app-1.18.0\resources\app\src\package.js:99:21)
    at C:\Users\TienTran\AppData\Local\atom\app-1.18.0\resources\app\src\package.js:218:32
    at Package.module.exports.Package.activate (C:\Users\TienTran\AppData\Local\atom\app-1.18.0\resources\app\src\package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\TienTran\AppData\Local\atom\app-1.18.0\resources\app\src\package-manager.js:645:40)
    at C:\Users\TienTran\AppData\Local\atom\app-1.18.0\resources\app\src\package-manager.js:377:25
    at C:\Users\TienTran\AppData\Local\atom\app-1.18.0\resources\app\src\config.js:644:26
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\TienTran\AppData\Local\atom\app-1.18.0\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (C:\Users\TienTran\AppData\Local\atom\app-1.18.0\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (C:\Users\TienTran\AppData\Local\atom\app-1.18.0\resources\app\src\config.js:835:35)
    at Config.module.exports.Config.setRawValue (C:\Users\TienTran\AppData\Local\atom\app-1.18.0\resources\app\src\config.js:621:25)
    at Config.module.exports.Config.set (C:\Users\TienTran\AppData\Local\atom\app-1.18.0\resources\app\src\config.js:236:20)
    at Config.module.exports.Config.removeAtKeyPath (C:\Users\TienTran\AppData\Local\atom\app-1.18.0\resources\app\src\config.js:386:18)
    at Package.module.exports.Package.enable (C:\Users\TienTran\AppData\Local\atom\app-1.18.0\resources\app\src\package.js:84:32)
    at PackageManager.module.exports.PackageManager.enablePackage (C:\Users\TienTran\AppData\Local\atom\app-1.18.0\resources\app\src\package-manager.js:188:20)
    at HTMLButtonElement.enablementButtonClickHandler (C:\Users\TienTran\AppData\Local\atom\app-1.18.0\resources\app\node_modules\settings-view\lib\package-card.js:361:31)

**Comment by iamjouza** [comment]
I already have the same issue... Anyone know what we have to do ?

**Comment by samimetoui** [comment]
i have the same issue: composer is installed, php version is 7.1.8, composer and php are in the path

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package 0.25.6


### Stack Trace

Failed to activate the atom-autocomplete-php package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/event-kit/lib/composite-disposable.js:74:19)
    at CompositeDisposable.module.exports.CompositeDisposable.add (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/event-kit/lib/composite-disposable.js:43:17)
    at Object.consumeProvider (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/autocomplete-plus/lib/main.js:89:27)
    at Object.consumeProvider_2_0 (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/autocomplete-plus/lib/main.js:66:23)
    at Provider.module.exports.Provider.provide (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.module.exports.Package.activateServices (~/AppData/Local/atom/app-1.21.0/resources/app/src/package.js:446:77)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.21.0/resources/app/src/package.js:256:22)
    at ~/AppData/Local/atom/app-1.21.0/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.21.0/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.21.0/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.21.0/resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.21.0/resources/app/src/package-manager.js:690:42)
    at ~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (~/AppData/Local/atom/app-1.21.0/resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.21.0/resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
  4x -5:24.3.0 core:backspace (input.hidden-input)
     -5:12.5.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -5:07.6.0 editor:consolidate-selections (input.hidden-input)
     -5:07.6.0 core:cancel (input.hidden-input)
 10x -4:37.2.0 core:backspace (input.hidden-input)
     -3:12.9.0 editor:move-to-first-character-of-line (input.hidden-input)
  4x -3:12.6.0 core:delete (input.hidden-input)
  2x -2:56.8.0 core:backspace (input.hidden-input)
     -2:54.3.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -2:51.8.0 editor:consolidate-selections (input.hidden-input)
     -2:51.8.0 core:cancel (input.hidden-input)
     -2:04.4.0 core:backspace (input.hidden-input)
     -1:59.5.0 core:confirm (input.hidden-input)
  6x -1:56.5.0 core:backspace (input.hidden-input)
     -1:55.1.0 core:delete (input.hidden-input)
     -1:46.8.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-bootstrap4 1.4.0 
craft-twig 0.4.0 
emmet 2.4.3 
php-getters-setters 0.5.5 
php-twig 4.0.0 
```

**Comment by HariS3ldon** [comment]
Same problem here:

Atom 1.22.0
Php and Composer are installed and in the path.

```
TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/usr/lib/atom/node_modules/event-kit/lib/composite-disposable.js:74:13)
    at CompositeDisposable.module.exports.CompositeDisposable.add (/usr/lib/atom/node_modules/event-kit/lib/composite-disposable.js:43:11)
    at Object.consumeProvider (/usr/lib/atom/node_modules/autocomplete-plus/lib/main.js:84:21)
    at Object.consumeProvider_2_0 (/usr/lib/atom/node_modules/autocomplete-plus/lib/main.js:61:17)
    at Provider.module.exports.Provider.provide (/usr/lib/atom/node_modules/service-hub/lib/provider.js:34:52)
    at ServiceHub.module.exports.ServiceHub.provide (/usr/lib/atom/node_modules/service-hub/lib/service-hub.js:30:20)
    at Package.module.exports.Package.activateServices (/usr/lib/atom/src/package.js:444:71)
    at Package.module.exports.Package.activateNow (/usr/lib/atom/src/package.js:254:16)
    at /usr/lib/atom/src/package.js:223:32
    at Package.module.exports.Package.measure (/usr/lib/atom/src/package.js:97:15)
    at /usr/lib/atom/src/package.js:216:26
    at Package.module.exports.Package.activate (/usr/lib/atom/src/package.js:213:34)
    at PackageManager.activatePackage (/usr/lib/atom/src/package-manager.js:679:36)
    at packagesToEnable.forEach.name (/usr/lib/atom/src/package-manager.js:428:45)
    at Array.forEach (native)
    at disabledPackagesSubscription.config.onDidChange (/usr/lib/atom/src/package-manager.js:428:24)
    at /usr/lib/atom/src/config.js:691:20
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:141:28)
    at Config.module.exports.Config.emitChangeEvent (/usr/lib/atom/src/config.js:882:29)
    at Config.module.exports.Config.setRawValue (/usr/lib/atom/src/config.js:668:19)
    at Config.module.exports.Config.set (/usr/lib/atom/src/config.js:246:14)
    at Config.module.exports.Config.removeAtKeyPath (/usr/lib/atom/src/config.js:405:12)
    at Package.module.exports.Package.enable (/usr/lib/atom/src/package.js:82:26)
    at PackageManager.enablePackage (/usr/lib/atom/src/package-manager.js:234:12)
    at HTMLButtonElement.enablementButtonClickHandler (/usr/lib/atom/node_modules/settings-view/lib/package-card.js:353:25)
```

**Comment by peterrus** [comment]
duplicate of https://github.com/Peekmo/atom-autocomplete-php/issues/351

also experiencing this. 

Composer 1.5.2 on Ubuntu using PHP 7.0.22

edit: updated all my atom packages and the error was gone.

**Comment by baldawayash15** [comment]
Also experiencing the same issue

**Comment by rubo77** [comment]
> edit: updated all my atom packages and the error was gone.

thx, this fixed it here too. I had to type this in the terminal console:

    apm update

**Comment by Jeremy-DEJOUX** [comment]
same problem

**Comment by h-queiroz** [comment]
Same problem here still. Anyone found how to solve it?

**Comment by doman2661** [comment]
apm update doesn't help
