### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by pandanrain** [Peekmo/atom-autocomplete-php#374]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.2 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package 0.25.6

### Stack Trace

Uncaught Error: spawn EACCES

```
At internal/child_process.js:313

Error: spawn EACCES
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:399:9)
    at Object.execute (/packages/atom-autocomplete-php/lib/services/php-proxy.coffee:72:58)
    at Object.functions (/packages/atom-autocomplete-php/lib/services/php-proxy.coffee:190:14)
    at Object.clearCache (/packages/atom-autocomplete-php/lib/services/php-proxy.coffee:156:10)
    at /packages/atom-autocomplete-php/lib/services/php-proxy.coffee:264:14
    at /private/var/folders/b0/cxbzstb934s838xt4zvhhd8h0000gn/T/AppTranslocation/8CB3C289-3668-441B-B700-257E612D670F/d/Atom.app/Contents/Resources/app/src/config.js:693:26
    at Function.module.exports.Emitter.simpleDispatch (/private/var/folders/b0/cxbzstb934s838xt4zvhhd8h0000gn/T/AppTranslocation/8CB3C289-3668-441B-B700-257E612D670F/d/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/private/var/folders/b0/cxbzstb934s838xt4zvhhd8h0000gn/T/AppTranslocation/8CB3C289-3668-441B-B700-257E612D670F/d/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (/private/var/folders/b0/cxbzstb934s838xt4zvhhd8h0000gn/T/AppTranslocation/8CB3C289-3668-441B-B700-257E612D670F/d/Atom.app/Contents/Resources/app/src/config.js:884:35)
    at Config.module.exports.Config.setRawValue (/private/var/folders/b0/cxbzstb934s838xt4zvhhd8h0000gn/T/AppTranslocation/8CB3C289-3668-441B-B700-257E612D670F/d/Atom.app/Contents/Resources/app/src/config.js:670:25)
    at Config.module.exports.Config.set (/private/var/folders/b0/cxbzstb934s838xt4zvhhd8h0000gn/T/AppTranslocation/8CB3C289-3668-441B-B700-257E612D670F/d/Atom.app/Contents/Resources/app/src/config.js:248:20)
    at SettingsPanel.set (/private/var/folders/b0/cxbzstb934s838xt4zvhhd8h0000gn/T/AppTranslocation/8CB3C289-3668-441B-B700-257E612D670F/d/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-panel.js:237:27)
    at /private/var/folders/b0/cxbzstb934s838xt4zvhhd8h0000gn/T/AppTranslocation/8CB3C289-3668-441B-B700-257E612D670F/d/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-panel.js:315:24
    at Function.module.exports.Emitter.simpleDispatch (/private/var/folders/b0/cxbzstb934s838xt4zvhhd8h0000gn/T/AppTranslocation/8CB3C289-3668-441B-B700-257E612D670F/d/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/private/var/folders/b0/cxbzstb934s838xt4zvhhd8h0000gn/T/AppTranslocation/8CB3C289-3668-441B-B700-257E612D670F/d/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (/private/var/folders/b0/cxbzstb934s838xt4zvhhd8h0000gn/T/AppTranslocation/8CB3C289-3668-441B-B700-257E612D670F/d/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1699:26)
    at later (/private/var/folders/b0/cxbzstb934s838xt4zvhhd8h0000gn/T/AppTranslocation/8CB3C289-3668-441B-B700-257E612D670F/d/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/helpers.js:28:13)
```

### Commands

```
     -4:35.5.0 core:move-up (input.hidden-input)
     -4:35.2.0 snippets:next-tab-stop (input.hidden-input)
     -4:35.2.0 snippets:expand (input.hidden-input)
     -4:35.2.0 editor:indent (input.hidden-input)
 26x -3:36.2.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-ide-ui 0.7.1 
busy-signal 1.4.3 
editorconfig 2.2.2 
goto-definition 1.3.4 
ide-php 0.7.4 
intentions 1.1.5 
language-vue 0.23.1 
language-vue-component 0.5.0 
linter 2.2.0 
linter-php 1.5.1 
linter-ui-default 1.6.10 
php-cs-fixer 4.1.1 
php-integrator-autocomplete-plus 1.6.1 
php-integrator-base 3.1.0 
project-manager 3.3.5 
```

**Comment by GabiArzu** [comment]
got the same error

**Comment by azoom-n-t-thuat** [comment]
got the same error
