### ISSUE TITLE
Uncaught Error: Cannot find module 'jquery'

### ISSUE THREAD

**Issue by brenomendes** [Peekmo/atom-autocomplete-php#391]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package 0.25.6

### Stack Trace

Uncaught Error: Cannot find module 'jquery'

```
At module.js:545

Error: Cannot find module 'jquery'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.getClassSelectorFromEvent (/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:780:11)
    at ClassProvider.module.exports.ClassProvider.getSelectorFromEvent (/packages/atom-autocomplete-php/lib/tooltip/class-provider.coffee:71:26)
    at /packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:106:30)
    at HTMLDivElement.dispatch (/packages/atom-runner/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/atom-runner/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -2:39.3.0 core:copy (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.32.5 
atom-nodejs-snippets 2.1.1 
atom-quokka 1.0.79 
atom-runner 2.7.1 
atom-ternjs 0.18.3 
autocomplete-paths 2.12.2 
css-snippets 1.1.0 
es6-snippets 0.3.0 
file-icons 2.1.22 
open-recent 5.0.0 
pigments 0.40.2 
scss-snippets 0.6.0 
```

**Comment by danialtajalli** [comment]
Ubuntu. Same. php 8.
