### ISSUE TITLE
Uncaught TypeError: element.indexOf is not a function

### ISSUE THREAD

**Issue by hoangdangduy** [Peekmo/atom-autocomplete-php#394]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package 0.25.6

### Stack Trace

Uncaught TypeError: element.indexOf is not a function

```
At C:\Users\hoangdd\.atom\packages\atom-autocomplete-php\lib\services\php-file-parser.coffee:532

TypeError: element.indexOf is not a function
    at Object.parseStackClass (/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:532:24)
    at Object.getStackClasses (/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:459:17)
    at Object.getCalledClass (/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:28:21)
    at Object.getMemberContext (/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:679:28)
    at FunctionProvider.module.exports.FunctionProvider.getTooltipForWord (/packages/atom-autocomplete-php/lib/tooltip/function-provider.coffee:18:25)
    at FunctionProvider.module.exports.AbstractProvider.showPopoverFor (/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:108:24)
    at /packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:77:22)
    at HTMLDivElement.dispatch (/packages/atom-autocomplete-php/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/atom-autocomplete-php/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -1:28.4.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:24.7.0 core:move-left (input.hidden-input)
     -1:22 autocomplete-plus:confirm (input.hidden-input)
     -1:22 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -1:19.7.0 core:move-right (input.hidden-input)
     -1:18.2.0 core:move-left (input.hidden-input)
     -1:17.9.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -1:17.8.0 editor:newline (input.hidden-input)
  2x -1:13.6.0 core:backspace (input.hidden-input)
     -0:23.1.0 core:paste (input.hidden-input)
     -0:20.5.0 snippets:next-tab-stop (input.hidden-input)
     -0:20.5.0 snippets:expand (input.hidden-input)
     -0:20.5.0 editor:indent (input.hidden-input)
     -0:20.2.0 snippets:next-tab-stop (input.hidden-input)
     -0:20.2.0 snippets:expand (input.hidden-input)
     -0:20.2.0 editor:indent (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.32.5 
atom-bootstrap4 1.4.0 
atom-live-server 2.3.0 
atom-wordpress 0.3.0 
autocomplete-java 1.2.7 
autocomplete-wordpress-hooks 0.2.3 
css-snippets 1.1.0 
emmet 2.4.3 
v-bootstrap4 0.2.2 
wordpress 0.2.0 
wordpress-api 1.2.2 
wordpress-dictionary 4.4.0 
wordpress-suite 1.3.0 
wp-dev 0.3.5 
```

**Comment by hoangdangduy** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package 0.25.6


### Stack Trace

Uncaught TypeError: element.indexOf is not a function

```
At C:\Users\hoangdd\.atom\packages\atom-autocomplete-php\lib\services\php-file-parser.coffee:532

TypeError: element.indexOf is not a function
    at Object.parseStackClass (/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:532:24)
    at Object.getStackClasses (/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:459:17)
    at Object.getCalledClass (/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:28:21)
    at Object.getMemberContext (/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:679:28)
    at FunctionProvider.module.exports.FunctionProvider.getTooltipForWord (/packages/atom-autocomplete-php/lib/tooltip/function-provider.coffee:18:25)
    at FunctionProvider.module.exports.AbstractProvider.showPopoverFor (/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:108:24)
    at /packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:77:22)
    at HTMLDivElement.dispatch (/packages/atom-autocomplete-php/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/atom-autocomplete-php/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.33.1 
atom-bootstrap4 1.4.0 
atom-live-server 2.3.0 
atom-wordpress 0.3.0 
autocomplete-java 1.2.7 
autocomplete-wordpress-hooks 0.2.3 
css-snippets 1.1.0 
emmet 2.4.3 
v-bootstrap4 0.2.2 
wordpress 0.2.0 
wordpress-api 1.2.2 
wordpress-dictionary 4.4.0 
wordpress-suite 1.3.0 
wp-dev 0.3.5 
```
