### ISSUE TITLE
Uncaught TypeError: element.indexOf is not a function

### ISSUE THREAD

**Issue by ikaiser** [Peekmo/atom-autocomplete-php#397]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Mac OS X 10.12.6
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package 0.25.6

### Stack Trace

Uncaught TypeError: element.indexOf is not a function

```
At /Users/sacchettiroberto/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:532

TypeError: element.indexOf is not a function
    at Object.parseStackClass (/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:532:24)
    at Object.getStackClasses (/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:459:17)
    at Object.getCalledClass (/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:28:21)
    at Object.getMemberContext (/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:679:28)
    at FunctionProvider.module.exports.FunctionProvider.getTooltipForWord (/packages/atom-autocomplete-php/lib/tooltip/function-provider.coffee:18:25)
    at FunctionProvider.module.exports.AbstractProvider.showPopoverFor (/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:108:24)
    at /packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:77:22)
    at HTMLDivElement.dispatch (/packages/atom-autocomplete-php/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/atom-autocomplete-php/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  3x -5:23 core:save (input.hidden-input)
     -5:20.6.0 remote-ftp:upload-selected (input.hidden-input)
     -0:17.4.0 core:save (input.hidden-input)
     -0:15.6.0 core:close (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-autocomplete-php 0.25.6 
atom-beautify 0.33.4 
atom-clock 0.1.16 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-wordpress 0.3.0 
autoclose-html 0.23.0 
autocomplete-java 1.2.7 
autocomplete-modules 2.2.2 
autocomplete-php 0.3.7 
autocomplete-ruby 0.2.8 
autocomplete-swift 1.0.3 
autocomplete-wordpress-hooks 0.2.3 
busy-signal 1.4.3 
codeigniter 0.3.2 
file-icons 2.1.25 
fonts 3.1.0 
git-history 3.3.0 
git-plus 8.1.0 
git-time-machine 2.1.0 
goto-definition 1.3.4 
hyperclick 0.1.5 
intentions 1.1.5 
java-generator 2.2.3 
javascript-snippets 1.2.1 
jquery-snippets 11.0.0 
language-leaf 0.1.1 
language-rspec 0.12.1 
language-swift 0.5.0 
language-vue 0.23.1 
language-vue-component 0.5.0 
language-vuejs 0.3.2 
linter 2.2.0 
linter-javac 1.9.4 
linter-php 1.5.1 
linter-rubocop 2.2.3 
linter-ruby 1.2.6 
linter-swiftc 2.0.0 
linter-ui-default 1.7.1 
linter-write-good 0.9.0 
monokai 0.24.0 
monokai-soft 0.2.0 
nord-atom-ui 0.11.0 
nucleus-dark-ui 0.12.3 
oceanic-next 1.0.0 
php-integrator-autocomplete-plus 1.6.2 
platformio-ide-terminal 2.8.4 
qolor 0.4.2 
rails-i18n-autocomplete 0.4.0 
rails-snippets 2.19.0 
remote-ftp 2.2.0 
ruby-solargraph 0.3.0 
script 3.18.1 
seti-ui 1.11.0 
split-diff 1.5.3 
svn 0.0.14 
swift-debugger 0.1.2 
sync-settings 0.8.6 
tabs-to-spaces 1.0.5 
todo-show 2.3.2 
vue-format 0.4.0 
vue2-autocomplete 0.1.0-alpha.4 
wordpress-api 1.2.2 
wordpress-suite 1.3.0 
```

**Comment by tux255** [comment]
Same for me

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.4
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package 0.25.6


### Stack Trace

Uncaught TypeError: element.indexOf is not a function

```
At /Users/haranin/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:532

TypeError: element.indexOf is not a function
    at Object.parseStackClass (/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:532:24)
    at Object.getStackClasses (/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:459:17)
    at Object.getCalledClass (/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:28:21)
    at Object.getMemberContext (/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:679:28)
    at FunctionProvider.module.exports.FunctionProvider.getTooltipForWord (/packages/atom-autocomplete-php/lib/tooltip/function-provider.coffee:18:25)
    at FunctionProvider.module.exports.AbstractProvider.showPopoverFor (/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:108:24)
    at /packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:77:22)
    at HTMLDivElement.dispatch (/packages/wordpress-suite/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/wordpress-suite/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -2:29.8.0 application:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -2:27.6.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  3x -2:22.8.0 core:backspace (input.hidden-input)
     -2:16.8.0 core:confirm (input.hidden-input)
     -1:28.5.0 atom-beautify:beautify-editor (div.line.cursor-line)
```

### Non-Core Packages

```
aligner 1.2.4 
aligner-css 1.2.1 
aligner-javascript 1.3.0 
aligner-php 1.3.0 
aligner-scss 1.3.1 
atom-autocomplete-php 0.25.6 
atom-beautify 0.33.4 
autocomplete-php 0.3.7 
busy-signal 2.0.1 
emmet 2.4.3 
git-merge 0.4.1 
goto-definition 1.3.4 
ide-php 0.7.18 
intentions 1.1.5 
language-dots 0.0.4 
linter 2.3.1 
linter-csslint 2.0.6 
linter-jscs 4.2.4 
linter-phpcs 1.7.6 
linter-ui-default 1.8.1 
merge-conflicts 1.4.5 
minimap 4.29.9 
php-cs-fixer 4.2.0 
todo-show 2.3.2 
wordpress-api 1.2.2 
wordpress-dictionary 4.4.0 
wordpress-suite 1.3.0 
xatom-debug-php 0.1.3 
```
