### ISSUE TITLE
Failed to activate the atom-autocomplete-php package

### ISSUE THREAD

**Issue by exuperok** [Peekmo/atom-autocomplete-php#40]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: elementary OS
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.5.0

### Stack Trace

Failed to activate the atom-autocomplete-php package

```
At EACCES: permission denied, open '/home/exupero/.atom/packages/atom-autocomplete-php/php/tmp.php'

Error: EACCES: permission denied, open '/home/exupero/.atom/packages/atom-autocomplete-php/php/tmp.php'
    at Error (native)
    at Object.fs.openSync (fs.js:544:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
    at Object.fs.writeFileSync (fs.js:1155:15)
    at Object.module.exports.writeConfig (/home/exupero/.atom/packages/atom-autocomplete-php/lib/config.coffee:41:17)
    at Object.module.exports.init (/home/exupero/.atom/packages/atom-autocomplete-php/lib/config.coffee:56:12)
    at Object.module.exports.activate (/home/exupero/.atom/packages/atom-autocomplete-php/lib/peekmo-php-atom-autocomplete.coffee:56:14)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:240:19)
    at /usr/share/atom/resources/app.asar/src/package.js:221:30
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:165:15)
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:213:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:452:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:436:29
    at Config.module.exports.Config.transact (/usr/share/atom/resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:431:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:412:46)
    at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom.js:645:21)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/window-bootstrap.js:12:8)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/window-bootstrap.js:23:4)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/usr/share/atom/resources/app.asar/src/babel.js:162:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:96:23)
    at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:36:7)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-ruby",
      "RubyMotion",
      "livescript-compile",
      "JSL",
      "JSL",
      "JSL",
      "livescript-compile",
      "JSL",
      "JSL",
      "JSL",
      "JSL",
      "JSL",
      "JSL",
      "JSL",
      "JSL",
      "JSL",
      "livescript-compile",
      "text-to-string-for-javascript-converter",
      "robin-language-php",
      "Modo",
      "language-javascript-subtlegradient",
      "language-python-django-templates",
      "linter-metascript",
      "robin-language-php",
      "ruby-slim",
      "text-to-string-for-javascript-converter",
      "live-doc-viewer",
      "linter-python-pyflakes",
      "linter-python-pep8"
    ]
  },
  "atom-autocomplete-php": {}
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
aligner-ruby, v1.4.0
atom-autocomplete-php, v0.5.0
atom-phpcs, v0.8.0
atom-python-debugger, v0.3.4
atom-ternjs, v0.6.8
autocomplete-php, v0.3.6
autocomplete-phpunit, v1.0.2
autocomplete-plus-python-jedi, v0.3.6
autocomplete-python, v0.5.1
autocomplete-ruby, v0.1.0
ember-cli-helper, v0.7.2
ember-snippets, v1.4.0
javascript-snippets, v1.0.0
jsformat, v0.9.0
jshint, v1.3.9
language-babel, v0.10.2
language-javascript-jsx, v0.3.7
linter, v1.2.4
linter-pep257, v0.2.1
linter-php, v0.0.15
linter-phpcs, v1.0.5
linter-phpmd, v0.0.11
linter-pylama, v0.1.4
linter-pylint, v0.2.2
linter-rubocop, v0.2.7
linter-ruby, v0.1.6
php-debug, v0.1.2
php-getters-setters, v0.5.5
php-introspector, v1.0.0
phpunit, v1.1.1
phpunit-snippets, v0.1.0
python-for-glyphs, v0.1.0
python-isort, v0.0.7
python-jedi, v0.3.0
python-yapf, v0.7.0
rhino-python, v0.6.2
robe, v0.1.0
ruby-block, v0.3.4
ruby-block-converter, v3.5.0
ruby-define-method, v0.2.1
script-runner, v1.8.3
sinatra-snippets, v1.4.0
standard-formatter, v1.0.0
symfony-snippets, v0.3.0

# Dev
No dev packages
```

**Comment by Peekmo** [comment]
Hello,

To be able to make the plugin works, the user need to have read and write access to /home/exupero/.atom/packages/atom-autocomplete-php

Please, make sure that you have this rights.

**Comment by Peekmo** [comment]
No answers so.. I close this issue.

Feel free to open a new one.

Regards,
Peekmo

**Comment by whyisjake** [comment]
I am seeing this error now too.
Plugin 0.20.2
Atom 1.12.7
Mac OS.

**Comment by Enerccio** [comment]
just got same error

**Comment by lucini** [comment]
same error here
Win10

**Comment by ksuhiyp** [comment]
same error here
ubuntu 16.10

**Comment by hexus** [comment]
Same, Windows 7.

**Comment by NAMSGithub** [comment]
Same, Mac OS X 10.11.6

There is no `/home/exupero/.atom/packages/atom-autocomplete-php` directory on my computer

Steps to reproduce:

Install package
or

Disable package
Enable package

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package 0.25.6


### Stack Trace

Failed to activate the atom-autocomplete-php package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/composite-disposable.js:74:19)
    at CompositeDisposable.module.exports.CompositeDisposable.add (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/composite-disposable.js:43:17)
    at requireAutocompleteManagerAsync (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/main.js:110:29)
    at Object.requireAutocompleteManagerAsync (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/main.js:31:15)
    at Object.consumeProvider (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/main.js:107:16)
    at Object.consumeProvider_2_0 (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/main.js:86:23)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app/src/package.js:446:77)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:256:22)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:377:25
    at /Applications/Atom.app/Contents/Resources/app/src/config.js:644:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/src/config.js:835:35)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:621:25)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app/src/config.js:236:20)
    at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:386:18)
    at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app/src/package.js:84:32)
    at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:188:20)
    at HTMLButtonElement.enablementButtonClickHandler (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:361:31)
```

### Commands

```
  3x -8:25.3.0 core:backspace (input.hidden-input)
  2x -8:21.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
```

**Comment by darron1217** [comment]
@lucini On window10 we should set composer's absolute path
ex) C:\ProgramData\ComposerSetup\bin\composer

In my case, I fixed it by setting composer's path.

**Comment by NAMSGithub** [comment]
@darron1217 that fixed it for me on mac OS x. In the settings i set composer's path to the composer.phar file. simple fix here.

**Comment by it-is-wednesday** [comment]
Fixed on Manjaro by setting composer's path to /usr/bin/composer (instead of /usr/local/bin/composer)
