### ISSUE TITLE
Update Package To Use New autocomplete-plus API

### ISSUE THREAD

**Issue by joefitzgerald** [Peekmo/atom-autocomplete-php#5]
Hi @Peekmo can you please update to the new autocomplete-plus API? https://github.com/atom-community/autocomplete-plus/wiki/Provider-API

The old API will be removed on Tuesday, February 10th, 2015.

**Comment by Peekmo** [comment]
Hello,

I'll take a look, thank you :)

**Comment by theblacklion** [comment]
:chocolate_bar:

**Comment by Peekmo** [comment]
:+1:

**Comment by theblacklion** [comment]
Today I updated Atom and it's modules. Is this being related to this issue?

**Atom Version**: 0.187.0
**System**: linux 3.13.0-46-generic
**Thrown From**: [autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.0.1

### Stack Trace

Failed to load the autocomplete-php package

```
At Cannot find module 'autocomplete-plus'

Error: Cannot find module 'autocomplete-plus'
    at Module._resolveFilename (module.js:351:15)
    at Function.Module._resolveFilename (/opt/atom/resources/app/src/module-cache.js:383:52)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/home/oktay/Projekte/atom/atom-autocomplete-php/lib/php-class-provider.coffee:6:10)
    at Object.<anonymous> (/home/oktay/Projekte/atom/atom-autocomplete-php/lib/php-class-provider.coffee:98:4)
    at Module._compile (module.js:475:26)
    at Object.requireCoffeeScript (/opt/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:370:32)
```

**Comment by Ciantic** [comment]
@theblacklion you should run "npm install" in the cloned directory.

However at the moment it doesn't work even after that, gives some other error when starting.

**Comment by Peekmo** [comment]
The package will be updated with the new autocomplete + library the next week. I was waiting for some new features that has been added.

**Comment by Peekmo** [comment]
The package has been ported to the new autocomplete+ API. 

New features will come soon.
