### ISSUE TITLE
Uncaught TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by DiHuang1986** [Peekmo/atom-autocomplete-php#60]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.4
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.7.0

### Stack Trace

Uncaught TypeError: Cannot read property 'indexOf' of undefined

```
At /Users/dihuang/.atom/packages/atom-autocomplete-php/lib/goto/property-goto.coffee:44

TypeError: Cannot read property 'indexOf' of undefined
  at GotoProperty.module.exports.GotoProperty.gotoFromWord (/Users/dihuang/.atom/packages/atom-autocomplete-php/lib/goto/property-goto.coffee:44:25)
  at GotoProperty.<anonymous> (/Users/dihuang/.atom/packages/atom-autocomplete-php/lib/goto/abstract-goto.coffee:130:30)
  at /Users/dihuang/.atom/packages/atom-autocomplete-php/lib/goto/abstract-goto.coffee:223:18
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.cursorMoved (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1595:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:56:31
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.notifyObservers (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:270:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:65:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:401:20)
  at Marker.module.exports.Marker.update (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:346:12)
  at Marker.module.exports.Marker.setHeadPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:143:19)
  at Marker.module.exports.Marker.setHeadBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:175:32)
  at Marker.module.exports.Marker.setHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:185:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:121:31
  at Cursor.module.exports.Cursor.changePosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:733:7)
  at Cursor.module.exports.Cursor.setScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:119:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1374:23
  at TextEditor.module.exports.TextEditor.moveCursors (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1586:9)
  at TextEditor.module.exports.TextEditor.setCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1373:19)
  at TextEditorComponent.module.exports.TextEditorComponent.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:552:25)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61)

```

### Commands

```
 18x -0:28.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:24.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:18.4.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:18.4.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:18.4.0 docblockr:parse-tab (atom-text-editor.editor.is-focused)
     -0:18.4.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:17.8.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:17.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:17.7.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:17.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:17.4.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:12.5.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:05.6.0 core:select-all (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:05.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:03.7.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:03.7.0 core:cancel (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "disabledPackages": [
      "tabs"
    ]
  },
  "atom-autocomplete-php": {}
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.7.0
atom-material-syntax, v0.2.3
atom-material-ui, v0.5.21
docblockr, v0.7.3
file-icons, v1.6.5
git-plus, v5.4.1

# Dev
No dev packages
```

**Comment by ValentinMerlet** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.10.5
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.18.1


### Stack Trace

Uncaught TypeError: Cannot read property 'indexOf' of undefined

```
At /Users/vmerlet/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:682

TypeError: Cannot read property 'indexOf' of undefined
    at Object.module.exports.getMemberContext (/Users/vmerlet/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:682:25)
    at FunctionProvider.module.exports.FunctionProvider.getTooltipForWord (/Users/vmerlet/.atom/packages/atom-autocomplete-php/lib/tooltip/function-provider.coffee:18:25)
    at FunctionProvider.module.exports.AbstractProvider.showPopoverFor (/Users/vmerlet/.atom/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:109:24)
    at HTMLSpanElement.<anonymous> (/Users/vmerlet/.atom/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:78:22)
    at HTMLDivElement.jQuery.event.dispatch (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -5:32.7.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -5:32.5.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -5:30.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -5:30.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -5:30.5.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -5:30.3.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -5:30.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:20.6.0 core:close (atom-text-editor.editor.is-focused)
     -5:19.7.0 core:copy (atom-text-editor.editor.is-focused)
     -5:19.4.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -5:19.2.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -5:18.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:59.1.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
  2x -0:54 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:52.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:06.3.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "unity-ui",
      "atom-light-syntax"
    ],
    "excludeVcsIgnoredPaths": false
  },
  "atom-autocomplete-php": {}
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.1
atom-symfony2, v0.2.1
auto-detect-indentation, v0.4.2
autocomplete-ionic-framework, v0.2.1
behat-atom, v0.1.2
close-other-tabs, v0.1.0
color-picker, v2.0.13
docblockr, v0.7.3
file-icons, v1.6.13
highlight-selected, v0.10.1
minimap-git-diff, v4.1.8
php-getters-setters, v0.5.5
php-twig, v4.0.0
sync-settings, v0.6.0
unity-ui, v2.1.2

# Dev
No dev packages
```
