### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by putude** [Peekmo/atom-autocomplete-php#61]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.7.1

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\putude\.atom\packages\atom-autocomplete-php\lib\services\php-file-parser.coffee:197

TypeError: Cannot read property 'length' of undefined
  at Object.module.exports.isInFunction (C:\Users\putude\.atom\packages\atom-autocomplete-php\lib\services\php-file-parser.coffee:197:65)
  at VariableProvider.module.exports.AbstractProvider.getSuggestions (C:\Users\putude\.atom\packages\atom-autocomplete-php\lib\providers\abstract-provider.coffee:21:52)
  at C:\Users\putude\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:267:56
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (C:\Users\putude\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:246:17)
  at AutocompleteManager.getSuggestionsFromProviders (C:\Users\putude\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3:61)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (C:\Users\putude\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:233:19)
  at C:\Users\putude\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3:61

```

### Commands

```
     -0:22.5.0 tree-view:collapse-directory (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:17.2.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:17.1.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:16.4.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:16.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:16.2.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:16.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:15.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:14.3.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:14.3.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:14.3.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:13.4.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:12.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:12.1.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:12.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:01.4.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "atom-autocomplete-php": {
    "binComposer": "composer"
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
atom-autocomplete-php, v0.7.1
atom-html-preview, v0.1.11
autocomplete-html-entities, v0.1.0
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
autocomplete-sass, v0.1.0
change-case, v0.6.0
color-picker, v2.0.11
emmet, v2.3.12
file-icons, v1.6.7
jquery-snippets, v11.0.0
linter, v1.4.3
linter-csslint, v1.0.5
linter-less, v2.1.0
linter-php, v1.0.3
pigments, v0.11.0
Remote-FTP, v0.7.2
text-manipulation, v0.6.0

# Dev
No dev packages
```

**Comment by Namek** [comment]
`atom-complete-php` version: `0.14.1`

```
Uncaught TypeError: Cannot read property 'length' of undefined
```

```
/C:/Users/Kamil/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:439
```

```
TypeError: Cannot read property 'length' of undefined
    at Object.module.exports.getVariableType (C:\Users\Kamil\.atom\packages\atom-autocomplete-php\lib\services\php-file-parser.coffee:508:32)
    at Object.module.exports.parseElements (C:\Users\Kamil\.atom\packages\atom-autocomplete-php\lib\services\php-file-parser.coffee:640:34)
    at Object.module.exports.getCalledClass (C:\Users\Kamil\.atom\packages\atom-autocomplete-php\lib\services\php-file-parser.coffee:34:17)
    at Object.module.exports.getMethodContext (C:\Users\Kamil\.atom\packages\atom-autocomplete-php\lib\services\php-file-parser.coffee:559:28)
    at FunctionProvider.module.exports.FunctionProvider.getTooltipForWord (C:\Users\Kamil\.atom\packages\atom-autocomplete-php\lib\tooltip\function-provider.coffee:18:25)
    at FunctionProvider.module.exports.AbstractProvider.showPopoverFor (C:\Users\Kamil\.atom\packages\atom-autocomplete-php\lib\tooltip\abstract-provider.coffee:108:24)
    at HTMLSpanElement.<anonymous> (C:\Users\Kamil\.atom\packages\atom-autocomplete-php\lib\tooltip\abstract-provider.coffee:77:22)
    at HTMLDivElement.jQuery.event.dispatch (C:\Users\Kamil\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (C:\Users\Kamil\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```


Atom says "This issue has already been reported".

**Comment by acburdine** [comment]
Yeah I had an issue with this as well. +1

I figured out a fix for it, not sure of its implications though

**Comment by acburdine** [comment]
this is fixed in master

**Comment by fkranenburg** [comment]
I have the version 0:15.0 and still receive this error.

```

**Atom Version**: 1.0.19
**System**: Microsoft Windows 10 Pro
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.15.0


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

At C:\Users\ferry2\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\fuzzaldrin\lib\filter.js:19

TypeError: Cannot read property 'length' of undefined
  at module.exports (C:\Users\ferry2\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\fuzzaldrin\lib\filter.js:19:38)
  at Object.module.exports.filter (C:\Users\ferry2\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\fuzzaldrin\lib\fuzzaldrin.js:21:14)
  at ClassProvider.module.exports.ClassProvider.gotoFromWord (C:\Users\ferry2\.atom\packages\atom-autocomplete-php\lib\goto\class-provider.coffee:30:31)
  at HTMLSpanElement.<anonymous> (C:\Users\ferry2\.atom\packages\atom-autocomplete-php\lib\goto\abstract-provider.coffee:133:22)
  at HTMLDivElement.jQuery.event.dispatch (C:\Users\ferry2\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at HTMLDivElement.elemData.handle (C:\Users\ferry2\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

**Comment by Peekmo** [comment]
With your stacktrace, it seems that it's fuzzaldrin library that throws the error.
Can't really do something for that.

How did you get this error @fkranenburg ?

**Comment by fkranenburg** [comment]
I got that error when I used CTRL+ALT+G to goto a definition. But autocomplete is not working at all in my Atom installation (CTRL+space does nothing when I input for example '$this-> '). I have all my settings set up correctly. Maybe other plugins are messing that up.

**Comment by Peekmo** [comment]
Is it a project managed with composer ?
Is your configuration ok ? (command : autocomplete php : configuration)

**Comment by fkranenburg** [comment]
I think my configuration is ok. My project is managed with composer. I'm on Windows and not sure why it does not work. This is currently my configuration:

![image](https://cloud.githubusercontent.com/assets/5680394/10711920/be10de5c-7a8a-11e5-8782-9d4ba41c9411.png)

**Comment by Peekmo** [comment]
Your binary for composer is incomplete.

Moreover, you don't have to put all the path to the autoloader file or classmap. Just put the relative ones (from your project). I guess that your project is in C:\eduthuis\laravel, so you can just keep the default values.

An example of working configuration is is the doc : https://github.com/Peekmo/atom-autocomplete-php#windows-wamp-and-composersetup

It should works for Laravel.

**Comment by fkranenburg** [comment]
Yes, that was the missing part. I is fully working now. Thank you for your support!

**Comment by doliver3** [comment]
Going through the first Laravel tutorial in the documentation, this error still occurs when holding the alt key and clicking the underline on the line 29 of routes.php

Uncaught TypeError: Cannot read property 'length' of undefined. 
/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzaldrin/lib/filter.js

TypeError: Cannot read property 'length' of undefined
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzaldrin/lib/filter.js:19:38)
    at Object.module.exports.filter (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzaldrin/lib/fuzzaldrin.js:21:14)
    at ClassProvider.module.exports.ClassProvider.gotoFromWord (/Users/beyondenergy/.atom/packages/atom-autocomplete-php/lib/goto/class-provider.coffee:30:31)
    at HTMLSpanElement.<anonymous> (/Users/beyondenergy/.atom/packages/atom-autocomplete-php/lib/goto/abstract-provider.coffee:133:22)
    at HTMLDivElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
