### ISSUE TITLE
Failed to load the atom-autocomplete-php package

### ISSUE THREAD

**Issue by Jackong** [Peekmo/atom-autocomplete-php#68]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.5
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.7.2

### Stack Trace

Failed to load the atom-autocomplete-php package

```
At Cannot find module 'fuzzaldrin'

Error: Cannot find module 'fuzzaldrin'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/daisy/.atom/packages/atom-autocomplete-php/lib/providers/class-provider.coffee:6:16)
    at Object.<anonymous> (/Users/daisy/.atom/packages/atom-autocomplete-php/lib/providers/class-provider.coffee:145:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "atom-autocomplete-php": {}
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.7.2
atom-material-syntax, v0.2.3
atom-material-ui, v0.6.0
autocomplete-modules, v1.1.0
docblockr, v0.7.3
imdone-atom, v1.1.32
linter, v1.4.3
react, v0.12.6
symbol-gen, v1.0.0
terminal-panel, v1.14.1

# Dev
No dev packages
```

**Comment by Peekmo** [comment]
Hello,

How did you install the package ?

**Comment by talgatbaltasov** [comment]
have same problem, installed by downloading from autocomplete-php repository, because i don't have administrator privilege at laptop and have some internet browsing limitation.

**Comment by Peekmo** [comment]
You have to do ```npm install``` (with nodejs installed) to be able to make it works when you download it from the repository.

**Comment by samtechie** [comment]
I installed the package from the Atom interface and am getting the same error.

**Comment by Peekmo** [comment]
I tried to install it, and it works (I'm on an older version of atom).

Perhaps a problem with the atom itself and fuzzaldrin package... I will try to take a look if I find the information. But nothing changed in this package dependencies since few months.

Regards,
Peekmo

**Comment by Peekmo** [comment]
There were a problem with npm. It should not be there anymore.
